//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef DOMAINTSDEMO_BASICBOOLEAN_ACE_H_
#define DOMAINTSDEMO_BASICBOOLEAN_ACE_H_

#include "DomainTSDemo/BasicBoolean.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure BasicBoolean
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainTSDemoIDL::BasicBoolean &data);

// de-serialization operator for DataStructure BasicBoolean
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainTSDemoIDL::BasicBoolean &data);

// serialization operator for CommunicationObject BasicBoolean
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const DomainTSDemo::BasicBoolean &obj);

// de-serialization operator for CommunicationObject BasicBoolean
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, DomainTSDemo::BasicBoolean &obj);

#endif /* DOMAINTSDEMO_BASICBOOLEAN_ACE_H_ */
