//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "DomainTSDemo/Coordinate3DPlusCore.hh"

// serialization/deserialization operators
//#include "DomainTSDemo/Coordinate3DPlusACE.hh"

// include the hash.idl containing the hash constant
#include "hash.hh"
#include <assert.h>
#include <cstring>
#include <iostream>

// SmartUtils used in from_xml method
#include "smartKnuthMorrisPratt.hh"

#ifdef ENABLE_HASH
	#include <boost/functional/hash.hpp>
#endif

namespace DomainTSDemo 
{
	const char* Coordinate3DPlusCore::getCompiledHash()
	{
		return DomainTSDemoIDL::REPO_HASH;
	}
	
	void Coordinate3DPlusCore::getAllHashValues(std::list<std::string> &hashes)
	{
		// get own hash value
		hashes.push_back(getCompiledHash());
		// get hash value(s) for CommBasicObjects::CommPosition3dWithCovariance(idl_Coordinate3DPlus.plus)
		CommBasicObjects::CommPosition3dWithCovariance::getAllHashValues(hashes);
	}
	
	void Coordinate3DPlusCore::checkAllHashValues(std::list<std::string> &hashes)
	{
		// check own hash value
		if (strcmp(getCompiledHash(), hashes.front().c_str()) != 0)
		{
			std::cerr << "###################################################" << std::endl;
			std::cerr << "WARNING: HASHES OF COMMUNICATION OBJECTS MISSMATCH!" << std::endl;
			std::cerr << "Coordinate3DPlusCore hash" << std::endl;
			std::cerr << "Expected: " << getCompiledHash() << std::endl;
			std::cerr << "Received: " << hashes.front() << std::endl;
			std::cerr << "###################################################" << std::endl;
		}
		assert(strcmp(getCompiledHash(), hashes.front().c_str()) == 0);
		hashes.pop_front();
		
		// check hash value(s) for CommBasicObjects::CommPosition3dWithCovariance(idl_Coordinate3DPlus.plus)
		CommBasicObjects::CommPosition3dWithCovariance::checkAllHashValues(hashes);
	}
	
	#ifdef ENABLE_HASH
	size_t Coordinate3DPlusCore::generateDataHash(const DATATYPE &data)
	{
		size_t seed = 0;
		
		boost::hash_combine(seed, data.x);
		boost::hash_combine(seed, data.y);
		boost::hash_combine(seed, data.z);
		seed += CommBasicObjects::CommPosition3dWithCovariance::generateDataHash(data.plus);
		
		return seed;
	}
	#endif
	
	// default constructor
	Coordinate3DPlusCore::Coordinate3DPlusCore()
	:	idl_Coordinate3DPlus()
	{  
		setX(0.0);
		setY(0.0);
		setZ(0.0);
		setPlus(CommBasicObjects::CommPosition3dWithCovariance());
	}
	
	Coordinate3DPlusCore::Coordinate3DPlusCore(const DATATYPE &data)
	:	idl_Coordinate3DPlus(data)
	{  }

	Coordinate3DPlusCore::~Coordinate3DPlusCore()
	{  }
	
	void Coordinate3DPlusCore::to_ostream(std::ostream &os) const
	{
	  os << "Coordinate3DPlus(";
	  os << getX() << " ";
	  os << getY() << " ";
	  os << getZ() << " ";
	  getPlus().to_ostream(os);
	  os << ") ";
	}
	
	// convert to xml stream
	void Coordinate3DPlusCore::to_xml(std::ostream &os, const std::string &indent) const {
		os << indent << "<x>" << getX() << "</x>";
		os << indent << "<y>" << getY() << "</y>";
		os << indent << "<z>" << getZ() << "</z>";
		os << indent << "<plus>";
		getPlus().to_xml(os, indent);
		os << indent << "</plus>";
	}
	
	// restore from xml stream
	void Coordinate3DPlusCore::from_xml(std::istream &is) {
		static const Smart::KnuthMorrisPratt kmp_x("<x>");
		static const Smart::KnuthMorrisPratt kmp_y("<y>");
		static const Smart::KnuthMorrisPratt kmp_z("<z>");
		static const Smart::KnuthMorrisPratt kmp_plus("<plus>");
		
		if(kmp_x.search(is)) {
			double xItem;
			is >> xItem;
			setX(xItem);
		}
		if(kmp_y.search(is)) {
			double yItem;
			is >> yItem;
			setY(yItem);
		}
		if(kmp_z.search(is)) {
			double zItem;
			is >> zItem;
			setZ(zItem);
		}
		if(kmp_plus.search(is)) {
			CommBasicObjects::CommPosition3dWithCovariance plusItem;
			plusItem.from_xml(is);
			setPlus(plusItem);
		}
	}
	
	/*
	void Coordinate3DPlusCore::get(ACE_Message_Block *&msg) const
	{
		// start with a default internal buffer size(will automatically grow if needed)
		ACE_OutputCDR cdr(ACE_DEFAULT_CDR_BUFSIZE);
		
		DomainTSDemoIDL::HashList hashes;
		getAllHashValues(hashes);
		cdr << static_cast<ACE_CDR::Long>(hashes.size());
		for(DomainTSDemoIDL::HashList::const_iterator it=hashes.begin(); it!=hashes.end(); it++)
		{
			cdr << ACE_CString(it->c_str());
		}
		
		// Here the actual serialization takes place using the OutputCDR serialization operator<<
		// (see Coordinate3DPlusACE.hh)
		cdr << idl_Coordinate3DPlus;
		
	#ifdef ENABLE_HASH
		ACE_CDR::ULong data_hash = generateDataHash(idl_Coordinate3DPlus);
		cdr << data_hash;
		// std::cout << "Coordinate3DPlusCore: current data hash: " << data_hash << std::endl;
	#endif
		
		// return a shallow copy of the serialized message 
		// (no data is actually copied, only the internal reference counter is incremented)
		// in order to prevent memory leaks the caller of this get(msg) method must
		// manually free the memory by calling the release() method of the message block msg
		msg = cdr.begin()->duplicate();
	}
	
	void Coordinate3DPlusCore::set(const ACE_Message_Block *msg)
	{
		ACE_InputCDR cdr(msg);
	
		DomainTSDemoIDL::HashList hashes;
		ACE_CDR::Long hashes_size;
		cdr >> hashes_size;
		for(int i=0; i<hashes_size; ++i) 
		{
			ACE_CString hash;
			cdr >> hash;
			hashes.push_back(hash.c_str());
		}
		checkAllHashValues(hashes);
		
		// Here the actual de-serialization takes place using the InputCDR serialization operator>>
		// (see Coordinate3DPlusACE.hh)
		cdr >> idl_Coordinate3DPlus;
		
	#ifdef ENABLE_HASH
		ACE_CDR::Long data_hash;
		cdr >> data_hash;
		ACE_CDR::Long own_hash = generateDataHash(idl_Coordinate3DPlus);
		assert(data_hash == own_hash);
		// std::cout << "Coordinate3DPlusCore: own data hash: " << own_hash << "; received data hash: " << data_hash << std::endl;
	#endif
	}
	*/
} /* namespace DomainTSDemo */
