//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _JOYSTICKSERVICEIN_4_UPCALL_MANAGER_HH
#define _JOYSTICKSERVICEIN_4_UPCALL_MANAGER_HH

#include <list>
#include "aceSmartSoft.hh"
#include "JoystickServiceIn_4UpcallInterface.hh"

/** JoystickServiceIn_4UpcallManager connects input-handling with Upcall propagation
 *
 * This class implements an InputHandler for the InputPort JoystickServiceIn_4 and propagates the handling 
 * of incoming data to all associated (i.e. attached) Upcalls.
 */
class JoystickServiceIn_4UpcallManager
:	public Smart::IInputHandler<CommBasicObjects::CommJoystick>
{
private:
	// list of associated updalls
	std::list<JoystickServiceIn_4UpcallInterface*> upcalls;

	// call the on_JoystickServiceIn_4 of all the attached JoystickServiceIn_4UpcallInterfaces
	void notify_upcalls(const CommBasicObjects::CommJoystick &input);
	
protected:
	virtual void handle_input(const CommBasicObjects::CommJoystick &input) {
		// relay input-handling to all attached JoystickServiceIn_4UpcallInterfaces
		this->notify_upcalls(input);
	}
public:
	JoystickServiceIn_4UpcallManager(
		Smart::InputSubject<CommBasicObjects::CommJoystick> *subject,
		const int &prescaleFactor=1
	);
	virtual ~JoystickServiceIn_4UpcallManager();
	
	void attach(JoystickServiceIn_4UpcallInterface *upcall);
	void detach(JoystickServiceIn_4UpcallInterface *upcall);
};

#endif
