//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommClosestNodeAnswerJSON.hh"

#include "CommBasicObjectsJSON/CommPosition3dJSON.hh"

namespace CommNavigationObjectsIDL {

void to_json(const CommNavigationObjectsIDL::CommClosestNodeAnswer& obj, nlohmann::json& j)
{
	// node_id: Int32
	j["node_id"] = obj.node_id;
	// position: CommPosition3d
	to_json(obj.position, j["position"]);
	// distance: Double
	j["distance"] = obj.distance;
	// valid: Boolean
	j["valid"] = obj.valid;
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommNavigationObjectsIDL::CommClosestNodeAnswer& obj)
{
	// node_id: Int32
	if(j.contains("node_id") && j["node_id"].is_number_integer()) {
		obj.node_id = j["node_id"].get<int>();
	}
	// position: CommPosition3d
	if(j.contains("position") && j["position"].is_object()) {
		//from_json(j["position"], obj.position);
		obj.position = j["position"].get<CommBasicObjectsIDL::CommPosition3d>();
	}
	// distance: Double
	if(j.contains("distance") && j["distance"].is_number_float()) {
		obj.distance = j["distance"].get<double>();
	}
	// valid: Boolean
	if(j.contains("valid") && j["valid"].is_boolean()) {
		obj.valid = j["valid"].get<bool>();
	}
}

} // end namespace CommNavigationObjectsIDL
