//================================================================
//
//  Copyright (c) 2021 Technische Hochschule Ulm, Servicerobotics Ulm, Germany
//
//        Servicerobotik Ulm 
//        Christian Schlegel
//        Ulm University of Applied Sciences
//        Prittwitzstr. 10
//        89075 Ulm
//        Germany
//
//	  http://www.servicerobotik-ulm.de/
//
//  This file is part of the Asset Administration Shell (SmartAAS) extension 
//  for SmartMDSD Toolchain.
//
//  Author:
//		Vineet Nagrath
//  Contributors:
//		Vineet Nagrath
//		Shaik Nayabrasul
//		Timo Blender
//		Jannik Rhode
//		Christian Schlegel
//
//  Licence:
//
//  BSD 3-Clause License
//  
//  Copyright (c) 2021, Servicerobotics Ulm
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//  
//  * Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//  
//  * Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//  
//  * Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//  https://opensource.org/licenses/BSD-3-Clause
//
//================================================================
package org.xtext.smartaas.technicaldata.generator;

public class SmartAASTechnicalDataDefaultContents {
	public String ProjectName	=	"SmartAASTechnicalDataDefaultContents";
	public String Copyright	=	"//================================================================\n"
			+ "//\n"
			+ "//  Copyright (c) 2021 Technische Hochschule Ulm, Servicerobotics Ulm, Germany\n"
			+ "//\n"
			+ "//        Servicerobotik Ulm \n"
			+ "//        Christian Schlegel\n"
			+ "//        Ulm University of Applied Sciences\n"
			+ "//        Prittwitzstr. 10\n"
			+ "//        89075 Ulm\n"
			+ "//        Germany\n"
			+ "//\n"
			+ "//	  http://www.servicerobotik-ulm.de/\n"
			+ "//\n"
			+ "//  File generated by Asset Administration Shell (SmartAAS) extension for SmartMDSD Toolchain.\n"
			+ "//\n"
			+ "//  Author:\n"
			+ "//	Vineet Nagrath\n"			
			+ "//  Contributors:\n"
			+ "//	Vineet Nagrath\n"
			+ "//	Shaik Nayabrasul\n"
			+ "//	Timo Blender\n"
			+ "//	Jannik Rhode\n"			
			+ "//	Christian Schlegel\n"
			+ "//\n"
			+ "//  Licence:\n"
			+ "//\n"
			+ "//  BSD 3-Clause License\n"
			+ "//  \n"
			+ "//  Copyright (c) 2021, Servicerobotics Ulm\n"
			+ "//  All rights reserved.\n"
			+ "//  \n"
			+ "//  Redistribution and use in source and binary forms, with or without\n"
			+ "//  modification, are permitted provided that the following conditions are met:\n"
			+ "//  \n"
			+ "//  * Redistributions of source code must retain the above copyright notice, this\n"
			+ "//    list of conditions and the following disclaimer.\n"
			+ "//  \n"
			+ "//  * Redistributions in binary form must reproduce the above copyright notice,\n"
			+ "//    this list of conditions and the following disclaimer in the documentation\n"
			+ "//    and/or other materials provided with the distribution.\n"
			+ "//  \n"
			+ "//  * Neither the name of the copyright holder nor the names of its\n"
			+ "//    contributors may be used to endorse or promote products derived from\n"
			+ "//    this software without specific prior written permission.\n"
			+ "//  \n"
			+ "//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
			+ "//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
			+ "//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
			+ "//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\n"
			+ "//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
			+ "//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
			+ "//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
			+ "//  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
			+ "//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
			+ "//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
			+ "//\n"
			+ "//  https://opensource.org/licenses/BSD-3-Clause\n"
			+ "//\n"
			+ "//================================================================\n"
			+ "//========Intermediate Model between SmartMDSD and SmartAAS=======\n";
	public String Footer	=	"//  File generated by Asset Administration Shell (SmartAAS) extension for SmartMDSD Toolchain.";
	public String DefaultContents	=	"{\n"
			+ "	GeneralInformation 				: 	\"GeneralInformation\"				[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/GeneralInformation/1/1\"]]\n"
			+ "	{\n"
			+ "		ManufacturerName			: 	\"ManufacturerName\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ManufacturerName/1/1\"]];\n"
			+ "		ManufacturerLogo			: 	\"ManufacturerLogo\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ManufacturerLogo/1/1\"]];	// OPTIONAL ENTRY\n"
			+ "		ManufacturerProductDesignation\n"
			+ "									: 	\"ManufacturerProductDesignation\"	[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ManufacturerProductDesignation/1/1\"]];\n"
			+ "		ManufacturerPartNumber		: 	\"ManufacturerPartNumber\"			[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ManufacturerPartNumber/1/1\"]];\n"
			+ "		ManufacturerOrderCode		: 	\"ManufacturerOrderCode\"				[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ManufacturerOrderCode/1/1\"]];\n"
			+ "		ProductImage				: 	\"ProductImage01\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductImage/1/1\"]];	// OPTIONAL ENTRY\n"
			+ "		ProductImage				: 	\"ProductImage02\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductImage/1/1\"]];	// OPTIONAL ENTRY\n"
			+ "		// Any number of \"ProductImage\" Entries can be added here\n"
			+ "	};\n"
			+ "	ProductClassifications 			: 	\"ProductClassifications\"			[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassifications/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "	{\n"
			+ "		ProductClassificationItem	: 	\"ProductClassificationItem01\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassificationItem/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			ProductClassificationSystem\n"
			+ "									: 	\"ProductClassificationSystem\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassificationSystem/1/1\"]];\n"
			+ "			ClassificationSystemVersion\n"
			+ "									: 	\"ClassificationSystemVersion\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ClassificationSystemVersion/1/1\"]];	// OPTIONAL ENTRY\n"
			+ "			ProductClassId			: 	\"ProductClassId\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassId/1/1\"]];\n"
			+ "		};\n"
			+ "		ProductClassificationItem	: 	\"ProductClassificationItem02\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassificationItem/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			ProductClassificationSystem\n"
			+ "									: 	\"ProductClassificationSystem\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassificationSystem/1/1\"]];\n"
			+ "			ClassificationSystemVersion\n"
			+ "									: 	\"ClassificationSystemVersion\"		[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ClassificationSystemVersion/1/1\"]];	// OPTIONAL ENTRY\n"
			+ "			ProductClassId			: 	\"ProductClassId\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ProductClassId/1/1\"]];\n"
			+ "		};\n"
			+ "		// Any number of \"ProductClassificationItem\" Entries can be added here		\n"
			+ "	};\n"
			+ "	TechnicalProperties 			: 	\"TechnicalProperties\"				[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/TechnicalProperties/1/1\"]]\n"
			+ "	{\n"
			+ "		Arbitrary					: 	\"Arbitrary01\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "		Arbitrary					: 	\"Arbitrary02\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "		// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "		Section						: 	\"Section01\"							[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/MainSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			Arbitrary				: 	\"Arbitrary03\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			Arbitrary				: 	\"Arbitrary04\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			SubSection				: 	\"SubSection01\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary05\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary06\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "				SubSection			: 	\"SubSection02\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "				{\n"
			+ "					Arbitrary		: 	\"Arbitrary07\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "					Arbitrary		: 	\"Arbitrary08\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "					// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "				};\n"
			+ "			};\n"
			+ "		};\n"
			+ "		Section						: 	\"Section02\"							[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/MainSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			Arbitrary				: 	\"Arbitrary09\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			Arbitrary				: 	\"Arbitrary10\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			SubSection				: 	\"SubSection03\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary11\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary12\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "				SubSection			: 	\"SubSection04\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "				{\n"
			+ "					Arbitrary		: 	\"Arbitrary13\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "					Arbitrary		: 	\"Arbitrary14\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "					// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "				};\n"
			+ "				// Any number of \"SubSection\" Entries can be added here\n"
			+ "			};\n"
			+ "			// Any number of \"Section\" Entries can be added here\n"
			+ "		};\n"
			+ "		// Any number of \"SubSection\" Entries can be added here\n"
			+ "		SubSection					: 	\"SubSection05\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			Arbitrary				: 	\"Arbitrary15\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			Arbitrary				: 	\"Arbitrary16\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			SubSection				: 	\"SubSection06\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary17\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary18\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			};\n"
			+ "			SubSection				: 	\"SubSection07\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary19\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary20\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			};\n"
			+ "			// Any number of \"SubSection\" Entries can be added here\n"
			+ "		};\n"
			+ "		SubSection					: 	\"SubSection08\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			Arbitrary				: 	\"Arbitrary21\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			Arbitrary				: 	\"Arbitrary22\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "			// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			SubSection				: 	\"SubSection09\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary23\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary24\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			};\n"
			+ "			SubSection				: 	\"SubSection10\"						[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/SubSection/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "			{\n"
			+ "				Arbitrary			: 	\"Arbitrary25\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				Arbitrary			: 	\"Arbitrary26\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "				// Any number of \"Arbitrary\" Entries can be added here\n"
			+ "			};\n"
			+ "			// Any number of \"SubSection\" Entries can be added here\n"
			+ "		};\n"
			+ "		// Any number of \"SubSection\" Entries can be added here\n"
			+ "	};\n"
			+ "	FurtherInformation 				: 	\"FurtherInformation\"				[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/FurtherInformation/1/1\"]]	// OPTIONAL ENTRY\n"
			+ "	{\n"
			+ "		TextStatement				: 	\"TextStatement01\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/TextStatement/1/1\"]];// OPTIONAL ENTRY\n"
			+ "		TextStatement				: 	\"TextStatement02\"					[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/TextStatement/1/1\"]];// OPTIONAL ENTRY\n"
			+ "		// Any number of \"TextStatement\" Entries can be added here\n"
			+ "		ValidDate					: 	\"ValidDate\"							[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/ValidDate/1/1\"]];\n"
			+ "	};	\n"
			+ "}";
	public String getFirstModelLine() {
		return "AAS :: TechnicalData	\"" + ProjectName + "\"	[[SemanticId : \"IRI\" | \"http://admin-shell.io/ZVEI/TechnicalData/Submodel/1/1\"]]";
	}
	public String getContents()	{
		return Copyright + "\n\n" + getFirstModelLine() + "\n" + DefaultContents + "\n" + Footer + "\n";
	};
}
