//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_CORE_H_
#define COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_CORE_H_

#include "CommLocalizationObjects/CommLocalizationZoneChangeData.hh"
#include "CommBasicObjects/CommTimeStamp.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommLocalizationObjects {
	
class CommLocalizationZoneChangeCore {
protected:
	// data structure
	CommLocalizationObjectsIDL::CommLocalizationZoneChange idl_CommLocalizationZoneChange;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommLocalizationObjectsIDL::CommLocalizationZoneChange DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommLocalizationZoneChangeCore();
	CommLocalizationZoneChangeCore(const DATATYPE &data);
	// default destructor
	virtual ~CommLocalizationZoneChangeCore();
	
	const DATATYPE& get() const { return idl_CommLocalizationZoneChange; }
	operator const DATATYPE&() const { return idl_CommLocalizationZoneChange; }
	DATATYPE& set() { return idl_CommLocalizationZoneChange; }

	static inline std::string identifier(void) { return "CommLocalizationObjects::CommLocalizationZoneChange"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element NewZone
	inline int getNewZone() const { return idl_CommLocalizationZoneChange.newZone; }
	inline CommLocalizationZoneChangeCore& setNewZone(const int &newZone) { idl_CommLocalizationZoneChange.newZone = newZone; return *this; }
	
	// getter and setter for element OldZone
	inline int getOldZone() const { return idl_CommLocalizationZoneChange.oldZone; }
	inline CommLocalizationZoneChangeCore& setOldZone(const int &oldZone) { idl_CommLocalizationZoneChange.oldZone = oldZone; return *this; }
	
	// getter and setter for element Timestamp
	inline CommBasicObjects::CommTimeStamp getTimestamp() const { return CommBasicObjects::CommTimeStamp(idl_CommLocalizationZoneChange.timestamp); }
	inline CommLocalizationZoneChangeCore& setTimestamp(const CommBasicObjects::CommTimeStamp &timestamp) { idl_CommLocalizationZoneChange.timestamp = timestamp; return *this; }
};

} /* namespace CommLocalizationObjects */
#endif /* COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_CORE_H_ */
