#--------------------------------------------------------------------------
# Code generated by the SmartSoft MDSD Toolchain
# The SmartSoft Toolchain has been developed by:
#  
# Service Robotics Research Center
# University of Applied Sciences Ulm
# Prittwitzstr. 10
# 89075 Ulm (Germany)
#
# Information about the SmartSoft MDSD Toolchain is available at:
# www.servicerobotik-ulm.de
#
# This file is generated once. Modify this file to your needs. 
# If you want the toolchain to re-generate this file, please 
# delete it before running the code generator.
#--------------------------------------------------------------------------

CMAKE_MINIMUM_REQUIRED(VERSION 3.0)
MESSAGE("-- Include DefaultCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/DefaultCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/DefaultCoordinationService)
MESSAGE("-- Include WebInterfaceCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/WebInterfaceCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/WebInterfaceCoordinationService)
MESSAGE("-- Include KBCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/KBCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/KBCoordinationService)
MESSAGE("-- Include LaserFromRGBDCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/LaserFromRGBDCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/LaserFromRGBDCoordinationService)
MESSAGE("-- Include VisualizationCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/VisualizationCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/VisualizationCoordinationService)
MESSAGE("-- Include SequencerHLCoordinationServer")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/SequencerHLCoordinationServer ${CMAKE_CURRENT_BINARY_DIR}/SequencerHLCoordinationServer)
MESSAGE("-- Include IRComponentCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/IRComponentCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/IRComponentCoordinationService)
MESSAGE("-- Include Seq2SeqComCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/Seq2SeqComCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/Seq2SeqComCoordinationService)
MESSAGE("-- Include FileOperationsCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/FileOperationsCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/FileOperationsCoordinationService)
MESSAGE("-- Include IOQueryCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/IOQueryCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/IOQueryCoordinationService)
MESSAGE("-- Include LaserSafetyCoordinationService")
ADD_SUBDIRECTORY(${CMAKE_CURRENT_LIST_DIR}/LaserSafetyCoordinationService ${CMAKE_CURRENT_BINARY_DIR}/LaserSafetyCoordinationService)
