/*
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.nameplate.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.smartaas.nameplate.ide.contentassist.antlr.internal.InternalDslParser;
import org.xtext.smartaas.nameplate.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getNameplateSubmodelAccess().getGroup(), "rule__NameplateSubmodel__Group__0");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getGroup_16(), "rule__NameplateSubmodel__Group_16__0");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getGroup_19(), "rule__NameplateSubmodel__Group_19__0");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getGroup_20(), "rule__NameplateSubmodel__Group_20__0");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerNameAccess().getGroup(), "rule__MultiLanguagePropertyManufacturerName__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getGroup(), "rule__MultiLanguagePropertyManufacturerProductDesignation__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductFamilyAccess().getGroup(), "rule__MultiLanguagePropertyManufacturerProductFamily__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertySerialNumberAccess().getGroup(), "rule__MultiLanguagePropertySerialNumber__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyYearOfConstructionAccess().getGroup(), "rule__MultiLanguagePropertyYearOfConstruction__Group__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup(), "rule__AddressSubmodelElementCollection__Group__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_7(), "rule__AddressSubmodelElementCollection__Group_7__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_12(), "rule__AddressSubmodelElementCollection__Group_12__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_13(), "rule__AddressSubmodelElementCollection__Group_13__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_16(), "rule__AddressSubmodelElementCollection__Group_16__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_19(), "rule__AddressSubmodelElementCollection__Group_19__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_20(), "rule__AddressSubmodelElementCollection__Group_20__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_21(), "rule__AddressSubmodelElementCollection__Group_21__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_22(), "rule__AddressSubmodelElementCollection__Group_22__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_23(), "rule__AddressSubmodelElementCollection__Group_23__0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getGroup_24(), "rule__AddressSubmodelElementCollection__Group_24__0");
			builder.put(grammarAccess.getMultiLanguagePropertyDepartmentAccess().getGroup(), "rule__MultiLanguagePropertyDepartment__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyStreetAccess().getGroup(), "rule__MultiLanguagePropertyStreet__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyZipcodeAccess().getGroup(), "rule__MultiLanguagePropertyZipcode__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyPOBoxAccess().getGroup(), "rule__MultiLanguagePropertyPOBox__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyZipCodeOfPOBoxAccess().getGroup(), "rule__MultiLanguagePropertyZipCodeOfPOBox__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyCityTownAccess().getGroup(), "rule__MultiLanguagePropertyCityTown__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyStateCountyAccess().getGroup(), "rule__MultiLanguagePropertyStateCounty__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyNationalCodeAccess().getGroup(), "rule__MultiLanguagePropertyNationalCode__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyVATNumberAccess().getGroup(), "rule__MultiLanguagePropertyVATNumber__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressRemarksAccess().getGroup(), "rule__MultiLanguagePropertyAddressRemarks__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressOfAdditionalLinkAccess().getGroup(), "rule__MultiLanguagePropertyAddressOfAdditionalLink__Group__0");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getGroup(), "rule__PhoneSubmodelElementCollection__Group__0");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getGroup_9(), "rule__PhoneSubmodelElementCollection__Group_9__0");
			builder.put(grammarAccess.getMultiLanguagePropertyTelephoneNumberAccess().getGroup(), "rule__MultiLanguagePropertyTelephoneNumber__Group__0");
			builder.put(grammarAccess.getPropertyTypeOfTelephoneAccess().getGroup(), "rule__PropertyTypeOfTelephone__Group__0");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getGroup(), "rule__FaxSubmodelElementCollection__Group__0");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getGroup_9(), "rule__FaxSubmodelElementCollection__Group_9__0");
			builder.put(grammarAccess.getMultiLanguagePropertyFaxAccess().getGroup(), "rule__MultiLanguagePropertyFax__Group__0");
			builder.put(grammarAccess.getPropertyTypeOfFaxNumberAccess().getGroup(), "rule__PropertyTypeOfFaxNumber__Group__0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getGroup(), "rule__EmailSubmodelElementCollection__Group__0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getGroup_9(), "rule__EmailSubmodelElementCollection__Group_9__0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getGroup_10(), "rule__EmailSubmodelElementCollection__Group_10__0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getGroup_10_2(), "rule__EmailSubmodelElementCollection__Group_10_2__0");
			builder.put(grammarAccess.getPropertyEmailAddressAccess().getGroup(), "rule__PropertyEmailAddress__Group__0");
			builder.put(grammarAccess.getPropertyTypeOfEmailAddressAccess().getGroup(), "rule__PropertyTypeOfEmailAddress__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyPublicKeyAccess().getGroup(), "rule__MultiLanguagePropertyPublicKey__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyTypeOfPublickKeyAccess().getGroup(), "rule__MultiLanguagePropertyTypeOfPublickKey__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingsAccess().getGroup(), "rule__SubmodelElementCollectionMarkings__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingsAccess().getGroup_7(), "rule__SubmodelElementCollectionMarkings__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getGroup(), "rule__SubmodelElementCollectionMarking__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getGroup_11(), "rule__SubmodelElementCollectionMarking__Group_11__0");
			builder.put(grammarAccess.getPropertyMarkingNameAccess().getGroup(), "rule__PropertyMarkingName__Group__0");
			builder.put(grammarAccess.getFileMarkingFileAccess().getGroup(), "rule__FileMarkingFile__Group__0");
			builder.put(grammarAccess.getPropertyMarkingAdditionalTextAccess().getGroup(), "rule__PropertyMarkingAdditionalText__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionAssetSpecificPropertiesAccess().getGroup(), "rule__SubmodelElementCollectionAssetSpecificProperties__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionAssetSpecificPropertiesAccess().getGroup_7(), "rule__SubmodelElementCollectionAssetSpecificProperties__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getGroup(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getGroup_9(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__Group_9__0");
			builder.put(grammarAccess.getPropertyGuidelineForConformityDeclarationAccess().getGroup(), "rule__PropertyGuidelineForConformityDeclaration__Group__0");
			builder.put(grammarAccess.getPropertyArbitraryAccess().getGroup(), "rule__PropertyArbitrary__Group__0");
			builder.put(grammarAccess.getSIDAccess().getGroup(), "rule__SID__Group__0");
			builder.put(grammarAccess.getModelAccess().getNameplateAssignment(), "rule__Model__NameplateAssignment");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getNameAssignment_3(), "rule__NameplateSubmodel__NameAssignment_3");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getSemanticIdAssignment_5(), "rule__NameplateSubmodel__SemanticIdAssignment_5");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getManufacturerNameAssignment_8(), "rule__NameplateSubmodel__ManufacturerNameAssignment_8");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getManufacturerProductDesignationAssignment_10(), "rule__NameplateSubmodel__ManufacturerProductDesignationAssignment_10");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getAddressAssignment_12(), "rule__NameplateSubmodel__AddressAssignment_12");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getManufacturerProductFamilyAssignment_14(), "rule__NameplateSubmodel__ManufacturerProductFamilyAssignment_14");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getSerialNumberAssignment_16_0(), "rule__NameplateSubmodel__SerialNumberAssignment_16_0");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getYearOfConstructionAssignment_17(), "rule__NameplateSubmodel__YearOfConstructionAssignment_17");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getMarkingsAssignment_19_0(), "rule__NameplateSubmodel__MarkingsAssignment_19_0");
			builder.put(grammarAccess.getNameplateSubmodelAccess().getAssetSpecificPropertiesAssignment_20_0(), "rule__NameplateSubmodel__AssetSpecificPropertiesAssignment_20_0");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerNameAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyManufacturerName__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerNameAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyManufacturerName__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyManufacturerProductDesignation__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyManufacturerProductDesignation__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductFamilyAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyManufacturerProductFamily__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductFamilyAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyManufacturerProductFamily__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertySerialNumberAccess().getNameAssignment_2(), "rule__MultiLanguagePropertySerialNumber__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertySerialNumberAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertySerialNumber__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyYearOfConstructionAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyYearOfConstruction__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyYearOfConstructionAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyYearOfConstruction__SemanticIdAssignment_4");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getNameAssignment_2(), "rule__AddressSubmodelElementCollection__NameAssignment_2");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getSemanticIdAssignment_4(), "rule__AddressSubmodelElementCollection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getDepartmentAssignment_7_0(), "rule__AddressSubmodelElementCollection__DepartmentAssignment_7_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getStreetAssignment_8(), "rule__AddressSubmodelElementCollection__StreetAssignment_8");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getZipcodeAssignment_10(), "rule__AddressSubmodelElementCollection__ZipcodeAssignment_10");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getPOBoxAssignment_12_0(), "rule__AddressSubmodelElementCollection__POBoxAssignment_12_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getZipCodeOfPOBoxAssignment_13_0(), "rule__AddressSubmodelElementCollection__ZipCodeOfPOBoxAssignment_13_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getCityTownAssignment_14(), "rule__AddressSubmodelElementCollection__CityTownAssignment_14");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getStateCountyAssignment_16_0(), "rule__AddressSubmodelElementCollection__StateCountyAssignment_16_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getNationalCodeAssignment_17(), "rule__AddressSubmodelElementCollection__NationalCodeAssignment_17");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getVATNumberAssignment_19_0(), "rule__AddressSubmodelElementCollection__VATNumberAssignment_19_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getAddressRemarksAssignment_20_0(), "rule__AddressSubmodelElementCollection__AddressRemarksAssignment_20_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getAddressOfAdditionalLinkAssignment_21_0(), "rule__AddressSubmodelElementCollection__AddressOfAdditionalLinkAssignment_21_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getPhoneAssignment_22_0(), "rule__AddressSubmodelElementCollection__PhoneAssignment_22_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getFaxAssignment_23_0(), "rule__AddressSubmodelElementCollection__FaxAssignment_23_0");
			builder.put(grammarAccess.getAddressSubmodelElementCollectionAccess().getEmailAssignment_24_0(), "rule__AddressSubmodelElementCollection__EmailAssignment_24_0");
			builder.put(grammarAccess.getMultiLanguagePropertyDepartmentAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyDepartment__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyDepartmentAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyDepartment__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyStreetAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyStreet__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyStreetAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyStreet__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyZipcodeAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyZipcode__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyZipcodeAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyZipcode__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyPOBoxAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyPOBox__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyPOBoxAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyPOBox__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyZipCodeOfPOBoxAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyZipCodeOfPOBox__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyZipCodeOfPOBoxAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyZipCodeOfPOBox__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyCityTownAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyCityTown__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyCityTownAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyCityTown__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyStateCountyAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyStateCounty__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyStateCountyAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyStateCounty__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyNationalCodeAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyNationalCode__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyNationalCodeAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyNationalCode__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyVATNumberAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyVATNumber__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyVATNumberAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyVATNumber__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressRemarksAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyAddressRemarks__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressRemarksAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyAddressRemarks__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressOfAdditionalLinkAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyAddressOfAdditionalLink__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyAddressOfAdditionalLinkAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyAddressOfAdditionalLink__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getNameAssignment_2(), "rule__PhoneSubmodelElementCollection__NameAssignment_2");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getSemanticIdAssignment_4(), "rule__PhoneSubmodelElementCollection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getTelephoneNumberAssignment_7(), "rule__PhoneSubmodelElementCollection__TelephoneNumberAssignment_7");
			builder.put(grammarAccess.getPhoneSubmodelElementCollectionAccess().getTypeOfTelephoneAssignment_9_0(), "rule__PhoneSubmodelElementCollection__TypeOfTelephoneAssignment_9_0");
			builder.put(grammarAccess.getMultiLanguagePropertyTelephoneNumberAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyTelephoneNumber__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyTelephoneNumberAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyTelephoneNumber__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyTypeOfTelephoneAccess().getNameAssignment_2(), "rule__PropertyTypeOfTelephone__NameAssignment_2");
			builder.put(grammarAccess.getPropertyTypeOfTelephoneAccess().getSemanticIdAssignment_4(), "rule__PropertyTypeOfTelephone__SemanticIdAssignment_4");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getNameAssignment_2(), "rule__FaxSubmodelElementCollection__NameAssignment_2");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getSemanticIdAssignment_4(), "rule__FaxSubmodelElementCollection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getFaxNumberAssignment_7(), "rule__FaxSubmodelElementCollection__FaxNumberAssignment_7");
			builder.put(grammarAccess.getFaxSubmodelElementCollectionAccess().getTypeOfFaxNumberAssignment_9_0(), "rule__FaxSubmodelElementCollection__TypeOfFaxNumberAssignment_9_0");
			builder.put(grammarAccess.getMultiLanguagePropertyFaxAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyFax__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyFaxAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyFax__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyTypeOfFaxNumberAccess().getNameAssignment_2(), "rule__PropertyTypeOfFaxNumber__NameAssignment_2");
			builder.put(grammarAccess.getPropertyTypeOfFaxNumberAccess().getSemanticIdAssignment_4(), "rule__PropertyTypeOfFaxNumber__SemanticIdAssignment_4");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getNameAssignment_2(), "rule__EmailSubmodelElementCollection__NameAssignment_2");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getSemanticIdAssignment_4(), "rule__EmailSubmodelElementCollection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getEmailAddressAssignment_7(), "rule__EmailSubmodelElementCollection__EmailAddressAssignment_7");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getTypeOfEmailAddressAssignment_9_0(), "rule__EmailSubmodelElementCollection__TypeOfEmailAddressAssignment_9_0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getPublicKeyAssignment_10_0(), "rule__EmailSubmodelElementCollection__PublicKeyAssignment_10_0");
			builder.put(grammarAccess.getEmailSubmodelElementCollectionAccess().getTypeOfPublickKeyAssignment_10_2_0(), "rule__EmailSubmodelElementCollection__TypeOfPublickKeyAssignment_10_2_0");
			builder.put(grammarAccess.getPropertyEmailAddressAccess().getNameAssignment_2(), "rule__PropertyEmailAddress__NameAssignment_2");
			builder.put(grammarAccess.getPropertyEmailAddressAccess().getSemanticIdAssignment_4(), "rule__PropertyEmailAddress__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyTypeOfEmailAddressAccess().getNameAssignment_2(), "rule__PropertyTypeOfEmailAddress__NameAssignment_2");
			builder.put(grammarAccess.getPropertyTypeOfEmailAddressAccess().getSemanticIdAssignment_4(), "rule__PropertyTypeOfEmailAddress__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyPublicKeyAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyPublicKey__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyPublicKeyAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyPublicKey__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyTypeOfPublickKeyAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyTypeOfPublickKey__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyTypeOfPublickKeyAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyTypeOfPublickKey__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingsAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionMarkings__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingsAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionMarkings__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingsAccess().getMarkingAssignment_7_0(), "rule__SubmodelElementCollectionMarkings__MarkingAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionMarking__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionMarking__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getMarkingNameAssignment_7(), "rule__SubmodelElementCollectionMarking__MarkingNameAssignment_7");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getMarkingFileAssignment_9(), "rule__SubmodelElementCollectionMarking__MarkingFileAssignment_9");
			builder.put(grammarAccess.getSubmodelElementCollectionMarkingAccess().getMarkingAdditionalTextAssignment_11_0(), "rule__SubmodelElementCollectionMarking__MarkingAdditionalTextAssignment_11_0");
			builder.put(grammarAccess.getPropertyMarkingNameAccess().getNameAssignment_2(), "rule__PropertyMarkingName__NameAssignment_2");
			builder.put(grammarAccess.getPropertyMarkingNameAccess().getSemanticIdAssignment_4(), "rule__PropertyMarkingName__SemanticIdAssignment_4");
			builder.put(grammarAccess.getFileMarkingFileAccess().getNameAssignment_2(), "rule__FileMarkingFile__NameAssignment_2");
			builder.put(grammarAccess.getFileMarkingFileAccess().getSemanticIdAssignment_4(), "rule__FileMarkingFile__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyMarkingAdditionalTextAccess().getNameAssignment_2(), "rule__PropertyMarkingAdditionalText__NameAssignment_2");
			builder.put(grammarAccess.getPropertyMarkingAdditionalTextAccess().getSemanticIdAssignment_4(), "rule__PropertyMarkingAdditionalText__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionAssetSpecificPropertiesAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionAssetSpecificProperties__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionAssetSpecificPropertiesAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionAssetSpecificProperties__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionAssetSpecificPropertiesAccess().getGuidelineSpecificPropertiesAssignment_7_0(), "rule__SubmodelElementCollectionAssetSpecificProperties__GuidelineSpecificPropertiesAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getGuidelineForConformityDeclarationAssignment_7(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__GuidelineForConformityDeclarationAssignment_7");
			builder.put(grammarAccess.getSubmodelElementCollectionGuidelineSpecificPropertiesAccess().getArbitraryAssignment_9_0(), "rule__SubmodelElementCollectionGuidelineSpecificProperties__ArbitraryAssignment_9_0");
			builder.put(grammarAccess.getPropertyGuidelineForConformityDeclarationAccess().getNameAssignment_2(), "rule__PropertyGuidelineForConformityDeclaration__NameAssignment_2");
			builder.put(grammarAccess.getPropertyGuidelineForConformityDeclarationAccess().getSemanticIdAssignment_4(), "rule__PropertyGuidelineForConformityDeclaration__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyArbitraryAccess().getNameAssignment_2(), "rule__PropertyArbitrary__NameAssignment_2");
			builder.put(grammarAccess.getPropertyArbitraryAccess().getSemanticIdAssignment_4(), "rule__PropertyArbitrary__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSIDAccess().getNameAssignment_2(), "rule__SID__NameAssignment_2");
			builder.put(grammarAccess.getSIDAccess().getIIAssignment_4(), "rule__SID__IIAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
