/*
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.command.ui;

import com.google.inject.Injector;
import org.eclipse.core.runtime.Platform;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.xtext.smartaas.command.ui.internal.CommandActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class DslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return Platform.getBundle(CommandActivator.PLUGIN_ID);
	}
	
	@Override
	protected Injector getInjector() {
		CommandActivator activator = CommandActivator.getInstance();
		return activator != null ? activator.getInjector(CommandActivator.ORG_XTEXT_SMARTAAS_COMMAND_DSL) : null;
	}

}
