//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef _SEND_COORDINATE2D_OUTPUT_PORT_TS_UPCALL_INTERFACE_HH
#define _SEND_COORDINATE2D_OUTPUT_PORT_TS_UPCALL_INTERFACE_HH

#include "DomainTSDemo/Coordinate2D.hh"

class Send_Coordinate2D_Output_Port_tsUpcallInterface {
public:
	virtual ~Send_Coordinate2D_Output_Port_tsUpcallInterface() {  }

	virtual void on_Send_Coordinate2D_Output_Port_ts(const DomainTSDemo::Coordinate2D &input) = 0;
};

#endif
