//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "EnforcerTemplateOpcUaBackendPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "CommBasicObjectsOpcUa/CommTaskEventStateOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/EnforcementInstructionPackageOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/EnforcementReplyPackageOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/EnforcementReportPackageOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/MemberIdentifierOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/SmartIN_CommandOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/SmartIN_EventTypeOpcUa.hh"

// create a static instance of the OpcUaBackendPortFactory
static EnforcerTemplateOpcUaBackendPortFactory OpcUaBackendPortFactory;

EnforcerTemplateOpcUaBackendPortFactory::EnforcerTemplateOpcUaBackendPortFactory()
{  
	componentImpl = 0;
	EnforcerTemplate::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

EnforcerTemplateOpcUaBackendPortFactory::~EnforcerTemplateOpcUaBackendPortFactory()
{  }

void EnforcerTemplateOpcUaBackendPortFactory::initialize(EnforcerTemplate *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int EnforcerTemplateOpcUaBackendPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&EnforcerTemplateOpcUaBackendPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}

Smart::ISendClientPattern<SmartInstitutionsServiceRepository::EnforcementInstructionPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementInstruction_Send()
{
	return new SeRoNet::OPCUA::Client::SendClient<SmartInstitutionsServiceRepository::EnforcementInstructionPackage>(componentImpl);
}

Smart::IPushClientPattern<SmartInstitutionsServiceRepository::EnforcementReplyPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementReply_Push()
{
	return new SeRoNet::OPCUA::Client::PushClient<SmartInstitutionsServiceRepository::EnforcementReplyPackage>(componentImpl);
}

Smart::IPushClientPattern<SmartInstitutionsServiceRepository::EnforcementReportPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementReport_Push()
{
	return new SeRoNet::OPCUA::Client::PushClient<SmartInstitutionsServiceRepository::EnforcementReportPackage>(componentImpl);
}

Smart::IQueryClientPattern<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcement_QueryRequester()
{
	return new SeRoNet::OPCUA::Client::QueryClient<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage>(componentImpl);
}

Smart::IEventClientPattern<SmartInstitutionsServiceRepository::SmartIN_Command, SmartInstitutionsServiceRepository::SmartIN_EventType> * EnforcerTemplateOpcUaBackendPortFactory::createEvent_Listener()
{
	return new SeRoNet::OPCUA::Client::EventClient<SmartInstitutionsServiceRepository::SmartIN_Command, SmartInstitutionsServiceRepository::SmartIN_EventType>(componentImpl);
}

Smart::IQueryClientPattern<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage> * EnforcerTemplateOpcUaBackendPortFactory::createReport_QueryRequester()
{
	return new SeRoNet::OPCUA::Client::QueryClient<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage>(componentImpl);
}


Smart::IPushServerPattern<SmartInstitutionsServiceRepository::EnforcementInstructionPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementInstruction_Push(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<SmartInstitutionsServiceRepository::EnforcementInstructionPackage>(componentImpl, serviceName);
}

Smart::ISendServerPattern<SmartInstitutionsServiceRepository::EnforcementReplyPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementReply_Send(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::SendServer<SmartInstitutionsServiceRepository::EnforcementReplyPackage>(componentImpl, serviceName);
}

Smart::ISendServerPattern<SmartInstitutionsServiceRepository::EnforcementReportPackage> * EnforcerTemplateOpcUaBackendPortFactory::createEnforcementReport_Send(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::SendServer<SmartInstitutionsServiceRepository::EnforcementReportPackage>(componentImpl, serviceName);
}

Smart::IEventServerPattern<SmartInstitutionsServiceRepository::SmartIN_Command, SmartInstitutionsServiceRepository::SmartIN_EventType, CommBasicObjects::CommTaskEventState> * EnforcerTemplateOpcUaBackendPortFactory::createEvent_Creator(const std::string &serviceName, std::shared_ptr<Smart::IEventTestHandler<SmartInstitutionsServiceRepository::SmartIN_Command, SmartInstitutionsServiceRepository::SmartIN_EventType, CommBasicObjects::CommTaskEventState>> event_CreatorEventTestHandler)
{
	return new SeRoNet::OPCUA::Server::EventServer<SmartInstitutionsServiceRepository::SmartIN_Command, SmartInstitutionsServiceRepository::SmartIN_EventType, CommBasicObjects::CommTaskEventState>(componentImpl, serviceName, event_CreatorEventTestHandler);
}


int EnforcerTemplateOpcUaBackendPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int EnforcerTemplateOpcUaBackendPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void EnforcerTemplateOpcUaBackendPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
