//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------

#include "DomainTSDemo/Coordinate3DPlus.hh"

using namespace DomainTSDemo;

Coordinate3DPlus::Coordinate3DPlus()
:	Coordinate3DPlusCore()
{  }


/**
 * Constructor to set all values.
 * NOTE that you have to keep this constructor consistent with the model!
 * Use  at your own choice.
 *
 * The preferred way to set values for initialization is:
 *      CommRepository::MyCommObject obj;
 *      obj.setX(1).setY(2).setZ(3)...;
Coordinate3DPlus::Coordinate3DPlus(const CommBasicObjects::CommPosition3dWithCovariance &plus, const double &x, const double &y, const double &z)
:	Coordinate3DPlusCore() // base constructor sets default values as defined in the model
{
	setX(x);
	setY(y);
	setZ(z);
	setPlus(plus);
}
 */

Coordinate3DPlus::Coordinate3DPlus(const Coordinate3DPlusCore &coordinate3DPlus)
:	Coordinate3DPlusCore(coordinate3DPlus)
{  }

Coordinate3DPlus::Coordinate3DPlus(const DATATYPE &coordinate3DPlus)
:	Coordinate3DPlusCore(coordinate3DPlus)
{  }

Coordinate3DPlus::~Coordinate3DPlus()
{  }
