//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#ifndef SMARTINJOYSTICKSERVER_PORTFACTORYINTERFACE_HH_
#define SMARTINJOYSTICKSERVER_PORTFACTORYINTERFACE_HH_

// include communication objects
#include <CommBasicObjects/CommJoystick.hh>
#include <CommBasicObjects/CommJoystickACE.hh>
#include <SmartInstitutionsServiceRepository/EnforcementReportPackage.hh>
#include <SmartInstitutionsServiceRepository/EnforcementReportPackageACE.hh>

#include <chrono>

// include component's main class
#include "SmartINJoystickServer.hh"

// forward declaration
class SmartINJoystickServer;

class SmartINJoystickServerPortFactoryInterface {
public:
	SmartINJoystickServerPortFactoryInterface() { };
	virtual ~SmartINJoystickServerPortFactoryInterface() { };

	virtual void initialize(SmartINJoystickServer *component, int argc, char* argv[]) = 0;
	virtual int onStartup() = 0;

	virtual Smart::ISendClientPattern<SmartInstitutionsServiceRepository::EnforcementReportPackage> * createEnforcementReport_Send() = 0;
	
	virtual Smart::IPushServerPattern<CommBasicObjects::CommJoystick> * createJoystickServcieOut(const std::string &serviceName) = 0;

	virtual int onShutdown(const std::chrono::steady_clock::duration &timeoutTime=std::chrono::seconds(2)) = 0;
	virtual void destroy() = 0;
};

#endif /* SMARTINJOYSTICKSERVER_PORTFACTORYINTERFACE_HH_ */
