/**
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.nameplate.dsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.Model#getNameplate <em>Nameplate</em>}</li>
 * </ul>
 *
 * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>Nameplate</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Nameplate</em>' containment reference list.
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getModel_Nameplate()
   * @model containment="true"
   * @generated
   */
  EList<NameplateSubmodel> getNameplate();

} // Model
