/**
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.nameplate.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nameplate Submodel</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getSemanticId <em>Semantic Id</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerName <em>Manufacturer Name</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerProductDesignation <em>Manufacturer Product Designation</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getAddress <em>Address</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerProductFamily <em>Manufacturer Product Family</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getSerialNumber <em>Serial Number</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getYearOfConstruction <em>Year Of Construction</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getMarkings <em>Markings</em>}</li>
 *   <li>{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getAssetSpecificProperties <em>Asset Specific Properties</em>}</li>
 * </ul>
 *
 * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel()
 * @model
 * @generated
 */
public interface NameplateSubmodel extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Semantic Id</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semantic Id</em>' containment reference.
   * @see #setSemanticId(SID)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_SemanticId()
   * @model containment="true"
   * @generated
   */
  SID getSemanticId();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getSemanticId <em>Semantic Id</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semantic Id</em>' containment reference.
   * @see #getSemanticId()
   * @generated
   */
  void setSemanticId(SID value);

  /**
   * Returns the value of the '<em><b>Manufacturer Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer Name</em>' containment reference.
   * @see #setManufacturerName(MultiLanguagePropertyManufacturerName)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_ManufacturerName()
   * @model containment="true"
   * @generated
   */
  MultiLanguagePropertyManufacturerName getManufacturerName();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerName <em>Manufacturer Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer Name</em>' containment reference.
   * @see #getManufacturerName()
   * @generated
   */
  void setManufacturerName(MultiLanguagePropertyManufacturerName value);

  /**
   * Returns the value of the '<em><b>Manufacturer Product Designation</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer Product Designation</em>' containment reference.
   * @see #setManufacturerProductDesignation(MultiLanguagePropertyManufacturerProductDesignation)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_ManufacturerProductDesignation()
   * @model containment="true"
   * @generated
   */
  MultiLanguagePropertyManufacturerProductDesignation getManufacturerProductDesignation();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerProductDesignation <em>Manufacturer Product Designation</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer Product Designation</em>' containment reference.
   * @see #getManufacturerProductDesignation()
   * @generated
   */
  void setManufacturerProductDesignation(MultiLanguagePropertyManufacturerProductDesignation value);

  /**
   * Returns the value of the '<em><b>Address</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Address</em>' containment reference.
   * @see #setAddress(AddressSubmodelElementCollection)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_Address()
   * @model containment="true"
   * @generated
   */
  AddressSubmodelElementCollection getAddress();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getAddress <em>Address</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Address</em>' containment reference.
   * @see #getAddress()
   * @generated
   */
  void setAddress(AddressSubmodelElementCollection value);

  /**
   * Returns the value of the '<em><b>Manufacturer Product Family</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Manufacturer Product Family</em>' containment reference.
   * @see #setManufacturerProductFamily(MultiLanguagePropertyManufacturerProductFamily)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_ManufacturerProductFamily()
   * @model containment="true"
   * @generated
   */
  MultiLanguagePropertyManufacturerProductFamily getManufacturerProductFamily();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getManufacturerProductFamily <em>Manufacturer Product Family</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Manufacturer Product Family</em>' containment reference.
   * @see #getManufacturerProductFamily()
   * @generated
   */
  void setManufacturerProductFamily(MultiLanguagePropertyManufacturerProductFamily value);

  /**
   * Returns the value of the '<em><b>Serial Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Serial Number</em>' containment reference.
   * @see #setSerialNumber(MultiLanguagePropertySerialNumber)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_SerialNumber()
   * @model containment="true"
   * @generated
   */
  MultiLanguagePropertySerialNumber getSerialNumber();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getSerialNumber <em>Serial Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Serial Number</em>' containment reference.
   * @see #getSerialNumber()
   * @generated
   */
  void setSerialNumber(MultiLanguagePropertySerialNumber value);

  /**
   * Returns the value of the '<em><b>Year Of Construction</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Year Of Construction</em>' containment reference.
   * @see #setYearOfConstruction(MultiLanguagePropertyYearOfConstruction)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_YearOfConstruction()
   * @model containment="true"
   * @generated
   */
  MultiLanguagePropertyYearOfConstruction getYearOfConstruction();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getYearOfConstruction <em>Year Of Construction</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Year Of Construction</em>' containment reference.
   * @see #getYearOfConstruction()
   * @generated
   */
  void setYearOfConstruction(MultiLanguagePropertyYearOfConstruction value);

  /**
   * Returns the value of the '<em><b>Markings</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Markings</em>' containment reference.
   * @see #setMarkings(SubmodelElementCollectionMarkings)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_Markings()
   * @model containment="true"
   * @generated
   */
  SubmodelElementCollectionMarkings getMarkings();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getMarkings <em>Markings</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Markings</em>' containment reference.
   * @see #getMarkings()
   * @generated
   */
  void setMarkings(SubmodelElementCollectionMarkings value);

  /**
   * Returns the value of the '<em><b>Asset Specific Properties</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Asset Specific Properties</em>' containment reference.
   * @see #setAssetSpecificProperties(SubmodelElementCollectionAssetSpecificProperties)
   * @see org.xtext.smartaas.nameplate.dsl.DslPackage#getNameplateSubmodel_AssetSpecificProperties()
   * @model containment="true"
   * @generated
   */
  SubmodelElementCollectionAssetSpecificProperties getAssetSpecificProperties();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.nameplate.dsl.NameplateSubmodel#getAssetSpecificProperties <em>Asset Specific Properties</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Asset Specific Properties</em>' containment reference.
   * @see #getAssetSpecificProperties()
   * @generated
   */
  void setAssetSpecificProperties(SubmodelElementCollectionAssetSpecificProperties value);

} // NameplateSubmodel
