//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_ACE_H_
#define SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_ACE_H_

#include "SmartInstitutions_ServiceRepository/EnforcementInstructionPackage.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure EnforcementInstructionPackage
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const SmartInstitutions_ServiceRepositoryIDL::EnforcementInstructionPackage &data);

// de-serialization operator for DataStructure EnforcementInstructionPackage
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, SmartInstitutions_ServiceRepositoryIDL::EnforcementInstructionPackage &data);

// serialization operator for CommunicationObject EnforcementInstructionPackage
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const SmartInstitutions_ServiceRepository::EnforcementInstructionPackage &obj);

// de-serialization operator for CommunicationObject EnforcementInstructionPackage
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, SmartInstitutions_ServiceRepository::EnforcementInstructionPackage &obj);

#endif /* SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_ACE_H_ */
