//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTREPLYPACKAGE_CORE_H_
#define SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTREPLYPACKAGE_CORE_H_

#include "SmartInstitutions_ServiceRepository/EnforcementReplyPackageData.hh"
#include "SmartInstitutions_ServiceRepository/InstitutionStatus.hh"
#include "SmartInstitutions_ServiceRepository/MemberIdentifier.hh"
#include "SmartInstitutions_ServiceRepository/PackageIdentifier.hh"

#include <iostream>
#include <string>
#include <list>

namespace SmartInstitutions_ServiceRepository {
	
class EnforcementReplyPackageCore {
protected:
	// data structure
	SmartInstitutions_ServiceRepositoryIDL::EnforcementReplyPackage idl_EnforcementReplyPackage;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef SmartInstitutions_ServiceRepositoryIDL::EnforcementReplyPackage DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	EnforcementReplyPackageCore();
	EnforcementReplyPackageCore(const DATATYPE &data);
	// default destructor
	virtual ~EnforcementReplyPackageCore();
	
	const DATATYPE& get() const { return idl_EnforcementReplyPackage; }
	operator const DATATYPE&() const { return idl_EnforcementReplyPackage; }
	DATATYPE& set() { return idl_EnforcementReplyPackage; }

	static inline std::string identifier(void) { return "SmartInstitutions_ServiceRepository::EnforcementReplyPackage"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Id
	inline SmartInstitutions_ServiceRepository::PackageIdentifier getId() const { return SmartInstitutions_ServiceRepository::PackageIdentifier(idl_EnforcementReplyPackage.id); }
	inline EnforcementReplyPackageCore& setId(const SmartInstitutions_ServiceRepository::PackageIdentifier &id) { idl_EnforcementReplyPackage.id = id; return *this; }
	
	// getter and setter for element Replyingto
	inline SmartInstitutions_ServiceRepository::PackageIdentifier getReplyingto() const { return SmartInstitutions_ServiceRepository::PackageIdentifier(idl_EnforcementReplyPackage.replyingto); }
	inline EnforcementReplyPackageCore& setReplyingto(const SmartInstitutions_ServiceRepository::PackageIdentifier &replyingto) { idl_EnforcementReplyPackage.replyingto = replyingto; return *this; }
	
	// getter and setter for element To
	inline SmartInstitutions_ServiceRepository::MemberIdentifier getTo() const { return SmartInstitutions_ServiceRepository::MemberIdentifier(idl_EnforcementReplyPackage.to); }
	inline EnforcementReplyPackageCore& setTo(const SmartInstitutions_ServiceRepository::MemberIdentifier &to) { idl_EnforcementReplyPackage.to = to; return *this; }
	
	// getter and setter for element From
	inline SmartInstitutions_ServiceRepository::MemberIdentifier getFrom() const { return SmartInstitutions_ServiceRepository::MemberIdentifier(idl_EnforcementReplyPackage.from); }
	inline EnforcementReplyPackageCore& setFrom(const SmartInstitutions_ServiceRepository::MemberIdentifier &from) { idl_EnforcementReplyPackage.from = from; return *this; }
	
	// getter and setter for element Context
	inline SmartInstitutions_ServiceRepository::InstitutionStatus getContext() const { return SmartInstitutions_ServiceRepository::InstitutionStatus(idl_EnforcementReplyPackage.context); }
	inline EnforcementReplyPackageCore& setContext(const SmartInstitutions_ServiceRepository::InstitutionStatus &context) { idl_EnforcementReplyPackage.context = context; return *this; }
	
	// getter and setter for element Reply
	inline std::string getReply() const { return idl_EnforcementReplyPackage.reply; }
	inline EnforcementReplyPackageCore& setReply(const std::string &reply) { idl_EnforcementReplyPackage.reply = reply; return *this; }
};

} /* namespace SmartInstitutions_ServiceRepository */
#endif /* SMARTINSTITUTIONS_SERVICEREPOSITORY_ENFORCEMENTREPLYPACKAGE_CORE_H_ */
