//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONS_SERVICEREPOSITORY_PACKAGEIDENTIFIER_DATA_H_
#define SMARTINSTITUTIONS_SERVICEREPOSITORY_PACKAGEIDENTIFIER_DATA_H_

#include "CommBasicObjects/CommTimeStampData.hh"


namespace SmartInstitutions_ServiceRepositoryIDL 
{
	struct PackageIdentifier
	{
		unsigned long int id;
		CommBasicObjectsIDL::CommTimeStamp timestampe;
  	};
};

#endif /* SMARTINSTITUTIONS_SERVICEREPOSITORY_PACKAGEIDENTIFIER_DATA_H_ */
