//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONSSERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_H_
#define SMARTINSTITUTIONSSERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_H_

#include "SmartInstitutionsServiceRepository/EnforcementInstructionPackageCore.hh"

namespace SmartInstitutionsServiceRepository {
		
class EnforcementInstructionPackage : public EnforcementInstructionPackageCore {
	public:
		// default constructors
		EnforcementInstructionPackage();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// EnforcementInstructionPackage(const SmartInstitutionsServiceRepository::PackageIdentifier &id, const std::vector<SmartInstitutionsServiceRepository::MemberIdentifier> &to, const SmartInstitutionsServiceRepository::MemberIdentifier &from, const SmartInstitutionsServiceRepository::InstitutionStatus &context, const SmartInstitutionsServiceRepository::EnforcementInstruction &instruction, const std::string &ifCustom);
		
		EnforcementInstructionPackage(const EnforcementInstructionPackageCore &enforcementInstructionPackage);
		EnforcementInstructionPackage(const DATATYPE &enforcementInstructionPackage);
		virtual ~EnforcementInstructionPackage();
		
		// use framework specific getter and setter methods from core (base) class
		using EnforcementInstructionPackageCore::get;
		using EnforcementInstructionPackageCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const EnforcementInstructionPackage &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace SmartInstitutionsServiceRepository */
#endif /* SMARTINSTITUTIONSSERVICEREPOSITORY_ENFORCEMENTINSTRUCTIONPACKAGE_H_ */
