//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTMESSAGE_H_
#define SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTMESSAGE_H_

#include "SmartInstitutionsServiceRepository/SmartIN_EventMessageCore.hh"

namespace SmartInstitutionsServiceRepository {
		
class SmartIN_EventMessage : public SmartIN_EventMessageCore {
	public:
		// default constructors
		SmartIN_EventMessage();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// SmartIN_EventMessage(const SmartInstitutionsServiceRepository::SmartINPackageTypeEnums &usetype, const SmartInstitutionsServiceRepository::EnforcementInstructionPackage &ifEnforcementInstructionPackage, const SmartInstitutionsServiceRepository::EnforcementReplyPackage &ifEnforcementReplyPackage, const SmartInstitutionsServiceRepository::EnforcementReportPackage &ifEnforcementReportPackage);
		
		SmartIN_EventMessage(const SmartIN_EventMessageCore &smartIN_EventMessage);
		SmartIN_EventMessage(const DATATYPE &smartIN_EventMessage);
		virtual ~SmartIN_EventMessage();
		
		// use framework specific getter and setter methods from core (base) class
		using SmartIN_EventMessageCore::get;
		using SmartIN_EventMessageCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const SmartIN_EventMessage &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace SmartInstitutionsServiceRepository */
#endif /* SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTMESSAGE_H_ */
