//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------

#include "SmartINJoystickManagerOpcUaBackendPortFactory.hh"

// include all potentially required pattern implementations
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/PushClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/EventClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QClientOPCUA.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/SendClient.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Client/QueryClient.hpp>

#include <SeRoNetSDK/SeRoNet/OPCUA/Server/PushServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/EventServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/SendServer.hpp>
#include <SeRoNetSDK/SeRoNet/OPCUA/Server/QueryServer.hpp>

// include referenced CommunicationObject SeRoNetSDK self description implementations
#include "CommBasicObjectsOpcUa/CommJoystickOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/EnforcementReportPackageOpcUa.hh"
#include "SmartInstitutionsServiceRepositoryOpcUa/MemberIdentifierOpcUa.hh"

// create a static instance of the OpcUaBackendPortFactory
static SmartINJoystickManagerOpcUaBackendPortFactory OpcUaBackendPortFactory;

SmartINJoystickManagerOpcUaBackendPortFactory::SmartINJoystickManagerOpcUaBackendPortFactory()
{  
	componentImpl = 0;
	SmartINJoystickManager::instance()->addPortFactory("OpcUa_SeRoNet", this);
}

SmartINJoystickManagerOpcUaBackendPortFactory::~SmartINJoystickManagerOpcUaBackendPortFactory()
{  }

void SmartINJoystickManagerOpcUaBackendPortFactory::initialize(SmartINJoystickManager *component, int argc, char* argv[])
{
	componentImpl = new SeRoNet::Utils::Component(component->connections.component.name);
}

int SmartINJoystickManagerOpcUaBackendPortFactory::onStartup()
{
	if (!component_thread.joinable()) {
    	component_thread = std::thread(&SmartINJoystickManagerOpcUaBackendPortFactory::task_execution, this);
    	return 0;
    }
	return -1;
}

Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceIn_1()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommJoystick>(componentImpl);
}

Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceIn_2()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommJoystick>(componentImpl);
}

Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceIn_3()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommJoystick>(componentImpl);
}

Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceIn_4()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommJoystick>(componentImpl);
}

Smart::IPushClientPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceIn_5()
{
	return new SeRoNet::OPCUA::Client::PushClient<CommBasicObjects::CommJoystick>(componentImpl);
}


Smart::IPushServerPattern<CommBasicObjects::CommJoystick> * SmartINJoystickManagerOpcUaBackendPortFactory::createJoystickServiceOut(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::PushServer<CommBasicObjects::CommJoystick>(componentImpl, serviceName);
}

Smart::IQueryServerPattern<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage> * SmartINJoystickManagerOpcUaBackendPortFactory::createReport_QueryResponder(const std::string &serviceName)
{
	return new SeRoNet::OPCUA::Server::QueryServer<SmartInstitutionsServiceRepository::MemberIdentifier, SmartInstitutionsServiceRepository::EnforcementReportPackage>(componentImpl, serviceName);
}


int SmartINJoystickManagerOpcUaBackendPortFactory::task_execution()
{
	componentImpl->run();
	return 0;
}

int SmartINJoystickManagerOpcUaBackendPortFactory::onShutdown(const std::chrono::steady_clock::duration &timeoutTime)
{
	// stop component-internal infrastructure
	componentImpl->stopRunning();
	// wait on component thread to exit
	if (component_thread.joinable()) {
		// FIXME: don't wait infinetly (use timeoutTime here)
    	component_thread.join();
    }
	return 0;
}

void SmartINJoystickManagerOpcUaBackendPortFactory::destroy()
{
	// clean-up component's internally used resources
	delete componentImpl;
}
