//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// This file is generated once. Modify this file to your needs. 
// If you want the toolchain to re-generate this file, please 
// delete it before running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_H_
#define COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_H_

#include "CommLocalizationObjects/CommLocalizationZoneChangeCore.hh"

namespace CommLocalizationObjects {
		
class CommLocalizationZoneChange : public CommLocalizationZoneChangeCore {
	public:
		// default constructors
		CommLocalizationZoneChange();
		
		/**
		 * Constructor to set all values.
		 * NOTE that you have to keep this constructor consistent with the model!
		 * Use  at your own choice.
		 *
		 * The preferred way to set values for initialization is:
		 *      CommRepository::MyCommObject obj;
		 *      obj.setX(1).setY(2).setZ(3)...;
		 */
		// CommLocalizationZoneChange(const int &newZone, const int &oldZone, const CommBasicObjects::CommTimeStamp &timestamp);
		
		CommLocalizationZoneChange(const CommLocalizationZoneChangeCore &commLocalizationZoneChange);
		CommLocalizationZoneChange(const DATATYPE &commLocalizationZoneChange);
		virtual ~CommLocalizationZoneChange();
		
		// use framework specific getter and setter methods from core (base) class
		using CommLocalizationZoneChangeCore::get;
		using CommLocalizationZoneChangeCore::set;
		
		//
		// feel free to add customized methods here
		//
};

inline std::ostream &operator<<(std::ostream &os, const CommLocalizationZoneChange &co)
{
	co.to_ostream(os);
	return os;
}
	
} /* namespace CommLocalizationObjects */
#endif /* COMMLOCALIZATIONOBJECTS_COMMLOCALIZATIONZONECHANGE_H_ */
