//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef COMMNAVIGATIONOBJECTS_COMMCORRIDORNAVIGATIONPATHANSWER_CORE_H_
#define COMMNAVIGATIONOBJECTS_COMMCORRIDORNAVIGATIONPATHANSWER_CORE_H_

#include "CommNavigationObjects/CommCorridorNavigationPathAnswerData.hh"
#include "CommNavigationObjects/CommNavigationPaths.hh"

#include <iostream>
#include <string>
#include <list>

namespace CommNavigationObjects {
	
class CommCorridorNavigationPathAnswerCore {
protected:
	// data structure
	CommNavigationObjectsIDL::CommCorridorNavigationPathAnswer idl_CommCorridorNavigationPathAnswer;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef CommNavigationObjectsIDL::CommCorridorNavigationPathAnswer DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	CommCorridorNavigationPathAnswerCore();
	CommCorridorNavigationPathAnswerCore(const DATATYPE &data);
	// default destructor
	virtual ~CommCorridorNavigationPathAnswerCore();
	
	const DATATYPE& get() const { return idl_CommCorridorNavigationPathAnswer; }
	operator const DATATYPE&() const { return idl_CommCorridorNavigationPathAnswer; }
	DATATYPE& set() { return idl_CommCorridorNavigationPathAnswer; }

	static inline std::string identifier(void) { return "CommNavigationObjects::CommCorridorNavigationPathAnswer"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Valid
	inline bool getValid() const { return idl_CommCorridorNavigationPathAnswer.valid; }
	inline CommCorridorNavigationPathAnswerCore& setValid(const bool &valid) { idl_CommCorridorNavigationPathAnswer.valid = valid; return *this; }
	
	// getter and setter for element Paths
	inline CommNavigationObjects::CommNavigationPaths getPaths() const { return CommNavigationObjects::CommNavigationPaths(idl_CommCorridorNavigationPathAnswer.paths); }
	inline CommCorridorNavigationPathAnswerCore& setPaths(const CommNavigationObjects::CommNavigationPaths &paths) { idl_CommCorridorNavigationPathAnswer.paths = paths; return *this; }
};

} /* namespace CommNavigationObjects */
#endif /* COMMNAVIGATIONOBJECTS_COMMCORRIDORNAVIGATIONPATHANSWER_CORE_H_ */
