//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#include "ComponentA.hh"
#include "smartTimedTaskTrigger.h"
//FIXME: implement logging
//#include "smartGlobalLogger.hh"

// the ace port-factory is used as a default port-mapping
#include "ComponentAAcePortFactory.hh"


// initialize static singleton pointer to zero
ComponentA* ComponentA::_componentA = 0;

// constructor
ComponentA::ComponentA()
{
	std::cout << "constructor of ComponentA\n";
	
	// set all pointer members to NULL
	//coordinationPortA = NULL;
	mainA = NULL;
	mainATrigger = NULL;
	push_Coordinate3D_Output_Port = NULL;
	queryValidCoordinate2DAnswHandler = NULL;
	query_ValidCoordinate2D_Answer_Port = NULL;
	query_ValidCoordinate2D_Answer_PortInputTaskTrigger = NULL;
	stateChangeHandler = NULL;
	stateSlave = NULL;
	wiringSlave = NULL;
	
	// set default ini parameter values
	connections.component.name = "ComponentA";
	connections.component.initialComponentMode = "Neutral";
	connections.component.defaultScheduler = "DEFAULT";
	connections.component.useLogger = false;
	
	connections.push_Coordinate3D_Output_Port.serviceName = "Push_Coordinate3D_Output_Port";
	connections.push_Coordinate3D_Output_Port.roboticMiddleware = "ACE_SmartSoft";
	connections.query_ValidCoordinate2D_Answer_Port.serviceName = "Query_ValidCoordinate2D_Answer_Port";
	connections.query_ValidCoordinate2D_Answer_Port.roboticMiddleware = "ACE_SmartSoft";
	connections.mainA.minActFreq = 0.0;
	connections.mainA.maxActFreq = 0.0;
	// scheduling default parameters
	connections.mainA.scheduler = "DEFAULT";
	connections.mainA.priority = -1;
	connections.mainA.cpuAffinity = -1;
	
	// initialize members of PlainOpcUaComponentAExtension
	
}

void ComponentA::addPortFactory(const std::string &name, ComponentAPortFactoryInterface *portFactory)
{
	portFactoryRegistry[name] = portFactory;
}

void ComponentA::addExtension(ComponentAExtension *extension)
{
	componentExtensionRegistry[extension->getName()] = extension;
}

SmartACE::SmartComponent* ComponentA::getComponentImpl()
{
	return dynamic_cast<ComponentAAcePortFactory*>(portFactoryRegistry["ACE_SmartSoft"])->getComponentImpl();
}

/**
 * Notify the component that setup/initialization is finished.
 * You may call this function from anywhere in the component.
 *
 * Set component's internal lifecycle state automaton (if any) into 
 * Alive mode (from here on the component is ready to provide its services)
 */
void ComponentA::setStartupFinished() {
	stateSlave->setWaitState("Alive");
	std::cout << "ComponentDefinition initialization/startup finished." << std::endl;
}




/**
 * First connect ALL client ports contained in this component, then start all services:
 * activate state, push, etc...
 */
Smart::StatusCode ComponentA::connectAndStartAllServices() {
	Smart::StatusCode status = Smart::SMART_OK;
	
	return status;
}

/**
 * Start all tasks contained in this component.
 */
void ComponentA::startAllTasks() {
	// start task MainA
	if(connections.mainA.scheduler != "DEFAULT") {
		ACE_Sched_Params mainA_SchedParams(ACE_SCHED_OTHER, ACE_THR_PRI_OTHER_DEF);
		if(connections.mainA.scheduler == "FIFO") {
			mainA_SchedParams.policy(ACE_SCHED_FIFO);
			mainA_SchedParams.priority(ACE_THR_PRI_FIFO_MIN);
		} else if(connections.mainA.scheduler == "RR") {
			mainA_SchedParams.policy(ACE_SCHED_RR);
			mainA_SchedParams.priority(ACE_THR_PRI_RR_MIN);
		}
		mainA->start(mainA_SchedParams, connections.mainA.cpuAffinity);
	} else {
		mainA->start();
	}
}

/**
 * Start all timers contained in this component
 */
void ComponentA::startAllTimers() {
}


Smart::TaskTriggerSubject* ComponentA::getInputTaskTriggerFromString(const std::string &client)
{
	
	return NULL;
}


void ComponentA::init(int argc, char *argv[])
{
	try {
		Smart::StatusCode status;
		
		// load initial parameters from ini-file (if found)
		loadParameter(argc, argv);
		
		
		// initializations of PlainOpcUaComponentAExtension
		
		
		// initialize all registered port-factories
		for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
		{
			portFactory->second->initialize(this, argc, argv);
		}
		
		// initialize all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->initialize(this, argc, argv);
		}
		
		ComponentAPortFactoryInterface *acePortFactory = portFactoryRegistry["ACE_SmartSoft"];
		if(acePortFactory == 0) {
			std::cerr << "ERROR: acePortFactory NOT instantiated -> exit(-1)" << std::endl;
			exit(-1);
		}
		
		// this pointer is used for backwards compatibility (deprecated: should be removed as soon as all patterns, including coordination, are moved to port-factory)
		SmartACE::SmartComponent *component = dynamic_cast<ComponentAAcePortFactory*>(acePortFactory)->getComponentImpl();
		
		std::cout << "ComponentDefinition ComponentA is named " << connections.component.name << std::endl;
		
		if(connections.component.useLogger == true) {
			//FIXME: use logging
			//Smart::LOGGER->openLogFileInFolder("data/"+connections.component.name);
			//Smart::LOGGER->startLogging();
		}

		// create event-test handlers (if needed)
		
		// create server ports
		// TODO: set minCycleTime from Ini-file
		push_Coordinate3D_Output_Port = portFactoryRegistry[connections.push_Coordinate3D_Output_Port.roboticMiddleware]->createPush_Coordinate3D_Output_Port(connections.push_Coordinate3D_Output_Port.serviceName);
		query_ValidCoordinate2D_Answer_Port = portFactoryRegistry[connections.query_ValidCoordinate2D_Answer_Port.roboticMiddleware]->createQuery_ValidCoordinate2D_Answer_Port(connections.query_ValidCoordinate2D_Answer_Port.serviceName);
		query_ValidCoordinate2D_Answer_PortInputTaskTrigger = new Smart::QueryServerTaskTrigger<DomainTSDemo::Coordinate2D, DomainTSDemo::BasicBoolean>(query_ValidCoordinate2D_Answer_Port);
		
		// create client ports
		
		// create InputTaskTriggers and UpcallManagers
		
		// create input-handler
		
		// create request-handlers
		queryValidCoordinate2DAnswHandler = new QueryValidCoordinate2DAnswHandler(query_ValidCoordinate2D_Answer_Port);
		
		// create state pattern
		stateChangeHandler = new SmartStateChangeHandler();
		stateSlave = new SmartACE::StateSlave(component, stateChangeHandler);
		status = stateSlave->setUpInitialState(connections.component.initialComponentMode);
		if (status != Smart::SMART_OK) std::cerr << status << "; failed setting initial ComponentMode: " << connections.component.initialComponentMode << std::endl;
		// activate state slave
		status = stateSlave->activate();
		if(status != Smart::SMART_OK) std::cerr << "ERROR: activate state" << std::endl;
		
		wiringSlave = new SmartACE::WiringSlave(component);
		// add client port to wiring slave
		
		
		
		// create Task MainA
		mainA = new MainA(component);
		// configure input-links
		// configure task-trigger (if task is configurable)
		if(connections.mainA.trigger == "PeriodicTimer") {
			// create PeriodicTimerTrigger
			int microseconds = 1000*1000 / connections.mainA.periodicActFreq;
			if(microseconds > 0) {
				Smart::TimedTaskTrigger *triggerPtr = new Smart::TimedTaskTrigger();
				triggerPtr->attach(mainA);
				component->getTimerManager()->scheduleTimer(triggerPtr, (void *) 0, std::chrono::microseconds(microseconds), std::chrono::microseconds(microseconds));
				// store trigger in class member
				mainATrigger = triggerPtr;
			} else {
				std::cerr << "ERROR: could not set-up Timer with cycle-time " << microseconds << " as activation source for Task MainA" << std::endl;
			}
		} else if(connections.mainA.trigger == "DataTriggered") {
			mainATrigger = getInputTaskTriggerFromString(connections.mainA.inPortRef);
			if(mainATrigger != NULL) {
				mainATrigger->attach(mainA, connections.mainA.prescale);
			} else {
				std::cerr << "ERROR: could not set-up InPort " << connections.mainA.inPortRef << " as activation source for Task MainA" << std::endl;
			}
		} 
		
		
		// link observers with subjects
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std exception" << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}

// run the component
void ComponentA::run()
{
	stateSlave->acquire("init");
	// startup all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onStartup();
	}
	
	// startup all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onStartup();
	}
	stateSlave->release("init");
	
	// do not call this handler within the init state (see above) as this handler internally calls setStartupFinished() (this should be fixed in future)
	compHandler.onStartup();
	
	// this call blocks until the component is commanded to shutdown
	stateSlave->acquire("shutdown");
	
	// shutdown all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->onShutdown();
	}
	
	// shutdown all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->onShutdown();
	}
	
	if(connections.component.useLogger == true) {
		//FIXME: use logging
		//Smart::LOGGER->stopLogging();
	}
	
	compHandler.onShutdown();
	
	stateSlave->release("shutdown");
}

// clean-up component's resources
void ComponentA::fini()
{
	// unlink all observers
	
	// destroy all task instances
	// unlink all UpcallManagers
	// unlink the TaskTrigger
	if(mainATrigger != NULL){
		mainATrigger->detach(mainA);
		delete mainA;
	}

	// destroy all input-handler

	// destroy InputTaskTriggers and UpcallManagers

	// destroy client ports

	// destroy server ports
	delete push_Coordinate3D_Output_Port;
	delete query_ValidCoordinate2D_Answer_Port;
	delete query_ValidCoordinate2D_Answer_PortInputTaskTrigger;
	// destroy event-test handlers (if needed)
	
	// destroy request-handlers
	delete queryValidCoordinate2DAnswHandler;
	
	delete stateSlave;
	// destroy state-change-handler
	delete stateChangeHandler;
	
	// destroy all master/slave ports
	delete wiringSlave;
	

	// destroy all registered component-extensions
	for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
	{
		extension->second->destroy();
	}

	// destroy all registered port-factories
	for(auto portFactory = portFactoryRegistry.begin(); portFactory != portFactoryRegistry.end(); portFactory++) 
	{
		portFactory->second->destroy();
	}
	
	// destruction of PlainOpcUaComponentAExtension
	
}

void ComponentA::loadParameter(int argc, char *argv[])
{
	/*
	 Parameters can be specified via command line --filename=<filename> or -f <filename>

	 With this parameter present:
	   - The component will look for the file in the current working directory,
	     a path relative to the current directory or any absolute path
	   - The component will use the default values if the file cannot be found

	 With this parameter absent:
	   - <Name of Component>.ini will be read from current working directory, if found there
	   - $SMART_ROOT/etc/<Name of Component>.ini will be read otherwise
	   - Default values will be used if neither found in working directory or /etc
	 */
	SmartACE::SmartIniParameter parameter;
	std::ifstream parameterfile;
	bool parameterFileFound = false;

	// load parameters
	try
	{
		// if paramfile is given as argument
		if(parameter.tryAddFileFromArgs(argc,argv,"filename", 'f'))
		{
			parameterFileFound = true;
			std::cout << "parameter file is loaded from an argv argument \n";
		} else if(parameter.searchFile("ComponentA.ini", parameterfile)) {
			parameterFileFound = true;
			std::cout << "load ComponentA.ini parameter file\n";
			parameter.addFile(parameterfile);
		} else {
			std::cout << "WARNING: ComponentA.ini parameter file not found! (using default values or command line arguments)\n";
		}
		
		// add command line arguments to allow overwriting of parameters
		// from file
		parameter.addCommandLineArgs(argc,argv,"component");
		
		// initialize the naming service using the command line parameters parsed in the
		// SmartIniParameter class. The naming service parameters are expected to be in
		// the "component" parameter group.
		SmartACE::NAMING::instance()->checkForHelpArg(argc,argv);
		if(parameterFileFound) 
		{
			if(SmartACE::NAMING::instance()->init(parameter.getAllParametersFromGroup("component")) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		} else {
			if(SmartACE::NAMING::instance()->init(argc, argv) != 0) {
				// initialization of naming service failed
				throw std::logic_error( "<NamingService> Service initialization failed!\nPossible causes could be:\n-> Erroneous configuration.\n-> Naming service not reachable.\n" );
			}
		}
			
		// print all known parameters
		// parameter.print();
		
		//--- server port // client port // other parameter ---
		// load parameter
		parameter.getString("component", "name", connections.component.name);
		parameter.getString("component", "initialComponentMode", connections.component.initialComponentMode);
		if(parameter.checkIfParameterExists("component", "defaultScheduler")) {
			parameter.getString("component", "defaultScheduler", connections.component.defaultScheduler);
		}
		if(parameter.checkIfParameterExists("component", "useLogger")) {
			parameter.getBoolean("component", "useLogger", connections.component.useLogger);
		}
		
		
		// load parameters for server Push_Coordinate3D_Output_Port
		parameter.getString("Push_Coordinate3D_Output_Port", "serviceName", connections.push_Coordinate3D_Output_Port.serviceName);
		if(parameter.checkIfParameterExists("Push_Coordinate3D_Output_Port", "roboticMiddleware")) {
			parameter.getString("Push_Coordinate3D_Output_Port", "roboticMiddleware", connections.push_Coordinate3D_Output_Port.roboticMiddleware);
		}
		// load parameters for server Query_ValidCoordinate2D_Answer_Port
		parameter.getString("Query_ValidCoordinate2D_Answer_Port", "serviceName", connections.query_ValidCoordinate2D_Answer_Port.serviceName);
		if(parameter.checkIfParameterExists("Query_ValidCoordinate2D_Answer_Port", "roboticMiddleware")) {
			parameter.getString("Query_ValidCoordinate2D_Answer_Port", "roboticMiddleware", connections.query_ValidCoordinate2D_Answer_Port.roboticMiddleware);
		}
		
		// load parameters for task MainA
		parameter.getDouble("MainA", "minActFreqHz", connections.mainA.minActFreq);
		parameter.getDouble("MainA", "maxActFreqHz", connections.mainA.maxActFreq);
		parameter.getString("MainA", "triggerType", connections.mainA.trigger);
		if(connections.mainA.trigger == "PeriodicTimer") {
			parameter.getDouble("MainA", "periodicActFreqHz", connections.mainA.periodicActFreq);
		} else if(connections.mainA.trigger == "DataTriggered") {
			parameter.getString("MainA", "inPortRef", connections.mainA.inPortRef);
			parameter.getInteger("MainA", "prescale", connections.mainA.prescale);
		}
		if(parameter.checkIfParameterExists("MainA", "scheduler")) {
			parameter.getString("MainA", "scheduler", connections.mainA.scheduler);
		}
		if(parameter.checkIfParameterExists("MainA", "priority")) {
			parameter.getInteger("MainA", "priority", connections.mainA.priority);
		}
		if(parameter.checkIfParameterExists("MainA", "cpuAffinity")) {
			parameter.getInteger("MainA", "cpuAffinity", connections.mainA.cpuAffinity);
		}
		
		// load parameters for PlainOpcUaComponentAExtension
		
		
		// load parameters for all registered component-extensions
		for(auto extension = componentExtensionRegistry.begin(); extension != componentExtensionRegistry.end(); extension++) 
		{
			extension->second->loadParameters(parameter);
		}
		
	
	} catch (const SmartACE::IniParameterError & e) {
		std::cerr << e.what() << std::endl;
	} catch (const std::exception &ex) {
		std::cerr << "Uncaught std::exception: " << ex.what() << std::endl;
	} catch (...) {
		std::cerr << "Uncaught exception" << std::endl;
	}
}
