//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONSSERVICEREPOSITORY_INSTITUTIONIDENTIFIER_CORE_H_
#define SMARTINSTITUTIONSSERVICEREPOSITORY_INSTITUTIONIDENTIFIER_CORE_H_

#include "SmartInstitutionsServiceRepository/InstitutionIdentifierData.hh"

#include <iostream>
#include <string>
#include <list>

namespace SmartInstitutionsServiceRepository {
	
class InstitutionIdentifierCore {
protected:
	// data structure
	SmartInstitutionsServiceRepositoryIDL::InstitutionIdentifier idl_InstitutionIdentifier;
	
public:
	// give a publicly accessible type-name for the template parameter IDL
	typedef SmartInstitutionsServiceRepositoryIDL::InstitutionIdentifier DATATYPE;
	
	#ifdef ENABLE_HASH
		static size_t generateDataHash(const DATATYPE &);
	#endif
	
	static const char* getCompiledHash();
	static void getAllHashValues(std::list<std::string> &hashes);
	static void checkAllHashValues(std::list<std::string> &hashes);
	
	// default constructors
	InstitutionIdentifierCore();
	InstitutionIdentifierCore(const DATATYPE &data);
	// default destructor
	virtual ~InstitutionIdentifierCore();
	
	const DATATYPE& get() const { return idl_InstitutionIdentifier; }
	operator const DATATYPE&() const { return idl_InstitutionIdentifier; }
	DATATYPE& set() { return idl_InstitutionIdentifier; }

	static inline std::string identifier(void) { return "SmartInstitutionsServiceRepository::InstitutionIdentifier"; }
	
	// helper method to easily implement output stream in derived classes
	void to_ostream(std::ostream &os = std::cout) const;
	
	// convert to xml stream
	void to_xml(std::ostream &os, const std::string &indent = "") const;
	
	// restore from xml stream
	void from_xml(std::istream &is);
	
	// User Interface
	
	// getter and setter for element Id
	inline unsigned long int getId() const { return idl_InstitutionIdentifier.id; }
	inline InstitutionIdentifierCore& setId(const unsigned long int &id) { idl_InstitutionIdentifier.id = id; return *this; }
	
	// getter and setter for element Name
	inline std::string getName() const { return idl_InstitutionIdentifier.name; }
	inline InstitutionIdentifierCore& setName(const std::string &name) { idl_InstitutionIdentifier.name = name; return *this; }
};

} /* namespace SmartInstitutionsServiceRepository */
#endif /* SMARTINSTITUTIONSSERVICEREPOSITORY_INSTITUTIONIDENTIFIER_CORE_H_ */
