//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_COMMAND_DATA_H_
#define SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_COMMAND_DATA_H_

#include "CommBasicObjects/CommTaskMessageData.hh"

#include <string>

namespace SmartInstitutionsServiceRepositoryIDL 
{
	struct SmartIN_Command
	{
		CommBasicObjectsIDL::CommTaskMessage msg;
		unsigned long int commandID;
		std::string command;
  	};
};

#endif /* SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_COMMAND_DATA_H_ */
