//--------------------------------------------------------------------------
// Code generated by the SmartSoft MDSD Toolchain
// The SmartSoft Toolchain has been developed by:
//  
// Service Robotics Research Center
// University of Applied Sciences Ulm
// Prittwitzstr. 10
// 89075 Ulm (Germany)
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//--------------------------------------------------------------------------
#ifndef SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTSTATETYPE_ACE_H_
#define SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTSTATETYPE_ACE_H_

#include "SmartInstitutionsServiceRepository/SmartIN_EventStateType.hh"

#include <ace/CDR_Stream.h>

// serialization operator for DataStructure SmartIN_EventStateType
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const SmartInstitutionsServiceRepositoryIDL::SmartIN_EventStateType &data);

// de-serialization operator for DataStructure SmartIN_EventStateType
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, SmartInstitutionsServiceRepositoryIDL::SmartIN_EventStateType &data);

// serialization operator for CommunicationObject SmartIN_EventStateType
ACE_CDR::Boolean operator<<(ACE_OutputCDR &cdr, const SmartInstitutionsServiceRepository::SmartIN_EventStateType &obj);

// de-serialization operator for CommunicationObject SmartIN_EventStateType
ACE_CDR::Boolean operator>>(ACE_InputCDR &cdr, SmartInstitutionsServiceRepository::SmartIN_EventStateType &obj);

#endif /* SMARTINSTITUTIONSSERVICEREPOSITORY_SMARTIN_EVENTSTATETYPE_ACE_H_ */
