/**
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.sms.dsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.smartaas.sms.dsl.Model#getSMSIN <em>SMSIN</em>}</li>
 *   <li>{@link org.xtext.smartaas.sms.dsl.Model#getSMSINCommand <em>SMSIN Command</em>}</li>
 * </ul>
 *
 * @see org.xtext.smartaas.sms.dsl.DslPackage#getModel()
 * @model
 * @generated
 */
public interface Model extends EObject
{
  /**
   * Returns the value of the '<em><b>SMSIN</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SMSIN</em>' containment reference.
   * @see #setSMSIN(SMSINType)
   * @see org.xtext.smartaas.sms.dsl.DslPackage#getModel_SMSIN()
   * @model containment="true"
   * @generated
   */
  SMSINType getSMSIN();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.sms.dsl.Model#getSMSIN <em>SMSIN</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SMSIN</em>' containment reference.
   * @see #getSMSIN()
   * @generated
   */
  void setSMSIN(SMSINType value);

  /**
   * Returns the value of the '<em><b>SMSIN Command</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>SMSIN Command</em>' containment reference.
   * @see #setSMSINCommand(SMSINTypeCommand)
   * @see org.xtext.smartaas.sms.dsl.DslPackage#getModel_SMSINCommand()
   * @model containment="true"
   * @generated
   */
  SMSINTypeCommand getSMSINCommand();

  /**
   * Sets the value of the '{@link org.xtext.smartaas.sms.dsl.Model#getSMSINCommand <em>SMSIN Command</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>SMSIN Command</em>' containment reference.
   * @see #getSMSINCommand()
   * @generated
   */
  void setSMSINCommand(SMSINTypeCommand value);

} // Model
