//================================================================
//
//  Copyright (c) 2021 Technische Hochschule Ulm, Servicerobotics Ulm, Germany
//
//        Servicerobotik Ulm 
//        Christian Schlegel
//        Ulm University of Applied Sciences
//        Prittwitzstr. 10
//        89075 Ulm
//        Germany
//
//	  http://www.servicerobotik-ulm.de/
//
//  This file is part of the Asset Administration Shell (SmartAAS) extension 
//  for SmartMDSD Toolchain.
//
//  Author:
//		Vineet Nagrath
//  Contributors:
//		Vineet Nagrath
//		Shaik Nayabrasul
//		Timo Blender
//		Jannik Rhode
//		Christian Schlegel
//
//  Licence:
//
//  BSD 3-Clause License
//  
//  Copyright (c) 2021, Servicerobotics Ulm
//  All rights reserved.
//  
//  Redistribution and use in source and binary forms, with or without
//  modification, are permitted provided that the following conditions are met:
//  
//  * Redistributions of source code must retain the above copyright notice, this
//    list of conditions and the following disclaimer.
//  
//  * Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//  
//  * Neither the name of the copyright holder nor the names of its
//    contributors may be used to endorse or promote products derived from
//    this software without specific prior written permission.
//  
//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
//  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
//
//  https://opensource.org/licenses/BSD-3-Clause
//
//================================================================
package org.xtext.smartaas.nameplate.generator;

public class SmartAASNameplateDefaultContents {
	public String ProjectName	=	"SmartAASNameplateDefaultContents";
	public String Copyright	=	"//================================================================\n"
			+ "//\n"
			+ "//  Copyright (c) 2021 Technische Hochschule Ulm, Servicerobotics Ulm, Germany\n"
			+ "//\n"
			+ "//        Servicerobotik Ulm \n"
			+ "//        Christian Schlegel\n"
			+ "//        Ulm University of Applied Sciences\n"
			+ "//        Prittwitzstr. 10\n"
			+ "//        89075 Ulm\n"
			+ "//        Germany\n"
			+ "//\n"
			+ "//	  http://www.servicerobotik-ulm.de/\n"
			+ "//\n"
			+ "//  File generated by Asset Administration Shell (SmartAAS) extension for SmartMDSD Toolchain.\n"
			+ "//\n"
			+ "//  Author:\n"
			+ "//	Vineet Nagrath\n"			
			+ "//  Contributors:\n"
			+ "//	Vineet Nagrath\n"
			+ "//	Shaik Nayabrasul\n"
			+ "//	Timo Blender\n"
			+ "//	Jannik Rhode\n"			
			+ "//	Christian Schlegel\n"
			+ "//\n"
			+ "//  Licence:\n"
			+ "//\n"
			+ "//  BSD 3-Clause License\n"
			+ "//  \n"
			+ "//  Copyright (c) 2021, Servicerobotics Ulm\n"
			+ "//  All rights reserved.\n"
			+ "//  \n"
			+ "//  Redistribution and use in source and binary forms, with or without\n"
			+ "//  modification, are permitted provided that the following conditions are met:\n"
			+ "//  \n"
			+ "//  * Redistributions of source code must retain the above copyright notice, this\n"
			+ "//    list of conditions and the following disclaimer.\n"
			+ "//  \n"
			+ "//  * Redistributions in binary form must reproduce the above copyright notice,\n"
			+ "//    this list of conditions and the following disclaimer in the documentation\n"
			+ "//    and/or other materials provided with the distribution.\n"
			+ "//  \n"
			+ "//  * Neither the name of the copyright holder nor the names of its\n"
			+ "//    contributors may be used to endorse or promote products derived from\n"
			+ "//    this software without specific prior written permission.\n"
			+ "//  \n"
			+ "//  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS \"AS IS\"\n"
			+ "//  AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE\n"
			+ "//  IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE\n"
			+ "//  DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE\n"
			+ "//  FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL\n"
			+ "//  DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR\n"
			+ "//  SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER\n"
			+ "//  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,\n"
			+ "//  OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE\n"
			+ "//  OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.\n"
			+ "//\n"
			+ "//  https://opensource.org/licenses/BSD-3-Clause\n"
			+ "//\n"
			+ "//================================================================";
	public String Footer	=	"//  File generated by Asset Administration Shell (SmartAAS) extension for SmartMDSD Toolchain.";
	public String DefaultContents	= "{\n"
			+ "	ManufacturerName 				: 	\"ManufacturerName\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO677#002\"]];\n"
			+ "	ManufacturerProductDesignation 	: 	\"ManufacturerProductDesignation\"[[SemanticId : \"IRDI\" | \"0173-1#02-AAW338#001\"]];\n"
			+ "	Address							:	\"AddressEntry\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ832#005\"]]\n"
			+ "	{\n"
			+ "		Department 					: 	\"Department\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAO127#003\"]];	// OPTIONAL ENTRY\n"
			+ "		Street 						: 	\"Street\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO128#002\"]];\n"
			+ "		Zipcode 					: 	\"Zipcode\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO129#002\"]];\n"
			+ "		POBox 						: 	\"POBox\"							[[SemanticId : \"IRDI\" | \"0173-1#02-AAO130#002\"]];	// OPTIONAL ENTRY\n"
			+ "		ZipCodeOfPOBox				: 	\"ZipCodeOfPOBox\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO131#002\"]];	// OPTIONAL ENTRY\n"
			+ "		CityTown 					: 	\"CityTown\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO132#002\"]];\n"
			+ "		StateCounty 				: 	\"StateCounty\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAO133#002\"]];	// OPTIONAL ENTRY\n"
			+ "		NationalCode				: 	\"NationalCode\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAO134#002\"]];\n"
			+ "		VATNumber 					: 	\"VATNumber\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO135#002\"]];	// OPTIONAL ENTRY\n"
			+ "		AddressRemarks				: 	\"AddressRemarks\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO202#003\"]];	// OPTIONAL ENTRY\n"
			+ "		AddressOfAdditionalLink 	: 	\"AddressOfAdditionalLink\"		[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ326#002\"]];	// OPTIONAL ENTRY\n"
			+ "		Phone						: 	\"Phone01\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ833#005\"]]\n"
			+ "		{\n"
			+ "			TelephoneNumber			:	\"TelephoneNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO136#002\"]];\n"
			+ "			TypeOfTelephone			:	\"TypeOfTelephone\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO137#003\"]];	// OPTIONAL ENTRY			\n"
			+ "		};\n"
			+ "		Phone						: 	\"Phone02\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ833#005\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			TelephoneNumber			:	\"TelephoneNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO136#002\"]];\n"
			+ "			TypeOfTelephone			:	\"TypeOfTelephone\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO137#003\"]];	// OPTIONAL ENTRY			\n"
			+ "		};\n"
			+ "		// Any number of \"Phone\" Entries can be added here\n"
			+ "		Fax							: 	\"Fax01\"							[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ834#005\"]]\n"
			+ "		{\n"
			+ "			FaxNumber				:	\"FaxNumber\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO195#002\"]];\n"
			+ "			TypeOfFaxNumber			:	\"TypeOfFaxNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO196#003\"]];	// OPTIONAL ENTRY			\n"
			+ "		};\n"
			+ "		Fax							: 	\"Fax02\"							[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ834#005\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			FaxNumber				:	\"FaxNumber\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO195#002\"]];\n"
			+ "			TypeOfFaxNumber			:	\"TypeOfFaxNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO196#003\"]];	// OPTIONAL ENTRY			\n"
			+ "		};\n"
			+ "		// Any number of \"Fax\" Entries can be added here\n"
			+ "		Email						: 	\"Email01\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ836#005\"]]\n"
			+ "		{\n"
			+ "			EmailAddress			:	\"EmailAddress\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAO198#002\"]];\n"
			+ "			TypeOfEmailAddress		:	\"TypeOfEmailNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO199#003\"]];	// OPTIONAL ENTRY			\n"
			+ "			PublicKey				:	\"PublicKey\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO200#002\"]];	// OPTIONAL ENTRY\n"
			+ "			TypeOfPublickKey		:	\"TypeOfPublickKey\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO201#002\"]];	// OPTIONAL ENTRY, Only When \"PublicKey is Defined\"\n"
			+ "		};\n"
			+ "		Email						: 	\"Email02\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAQ836#005\"]]\n"
			+ "		{\n"
			+ "			EmailAddress			:	\"EmailAddress\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAO198#002\"]];\n"
			+ "			TypeOfEmailAddress		:	\"TypeOfEmailNumber\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO199#003\"]];	// OPTIONAL ENTRY			\n"
			+ "			PublicKey				:	\"PublicKey\"						[[SemanticId : \"IRDI\" | \"0173-1#02-AAO200#002\"]];	// OPTIONAL ENTRY\n"
			+ "			TypeOfPublickKey		:	\"TypeOfPublickKey\"				[[SemanticId : \"IRDI\" | \"0173-1#02-AAO201#002\"]];	// OPTIONAL ENTRY, Only When \"PublicKey is Defined\"\n"
			+ "		};\n"
			+ "		// Any number of \"Email\" Entries can be added here\n"
			+ "	};\n"
			+ "	ManufacturerProductFamily 		: 	\"ManufacturerProductFamily\"		[[SemanticId : \"IRDI\" | \"0173-1#02-AAU731#001\"]];\n"
			+ "	SerialNumber 					: 	\"SerialNumber\"					[[SemanticId : \"IRDI\" | \"0173-1#02-AAM556#002\"]];	// OPTIONAL ENTRY\n"
			+ "	YearOfConstruction				: 	\"YearOfConstruction\"			[[SemanticId : \"IRDI\" | \"0173-1#02-AAP906#001\"]];\n"
			+ "	Markings 						: 	\"Markings\"						[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings\"]]	// OPTIONAL ENTRY\n"
			+ "	{\n"
			+ "		Marking						: 	\"Marking01\"						[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking\"]]\n"
			+ "		{\n"
			+ "			MarkingName				:	\"MarkingName\"					[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingName\"]];\n"
			+ "			MarkingFile				:	\"MarkingFile\"					[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingFile\"]];\n"
			+ "			MarkingAdditionalText	:	\"MarkingAdditionalText01A\"		[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingAdditionalText\"]];	// OPTIONAL ENTRY\n"
			+ "			MarkingAdditionalText	:	\"MarkingAdditionalText01B\"		[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingAdditionalText\"]];	// OPTIONAL ENTRY\n"
			+ "		};\n"
			+ "		Marking						: 	\"Marking02\"						[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			MarkingName				:	\"MarkingName\"					[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingName\"]];\n"
			+ "			MarkingFile				:	\"MarkingFile\"					[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingFile\"]];\n"
			+ "			MarkingAdditionalText	:	\"MarkingAdditionalText02A\"		[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingAdditionalText\"]];	// OPTIONAL ENTRY\n"
			+ "			MarkingAdditionalText	:	\"MarkingAdditionalText02B\"		[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/Markings/Marking/MarkingAdditionalText\"]];	// OPTIONAL ENTRY\n"
			+ "		};\n"
			+ "		// Any number of \"Marking\" Entries can be added here\n"
			+ "	};\n"
			+ "	AssetSpecificProperties			: 	\"AssetSpecificProperties\"		[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/AssetSpecificProperties\"]]	// OPTIONAL ENTRY\n"
			+ "	{\n"
			+ "		GuidelineSpecificProperties	: 	\"GuidelineSpecificProperties01\"	[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/AssetSpecificProperties/GuidelineSpecificProperties\"]]\n"
			+ "		{\n"
			+ "			GuidelineForConformityDeclaration\n"
			+ "									:	\"GuidelineForConformityDeclaration\"\n"
			+ "																		[[SemanticId : \"IRDI\" | \"0173-1#02-AAO856#002\"]];\n"
			+ "			Arbitrary				:	\"Arbitrary1\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];\n"
			+ "			Arbitrary				:	\"Arbitrary2\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "		};\n"
			+ "		GuidelineSpecificProperties	: 	\"GuidelineSpecificProperties02\"	[[SemanticId : \"IRI\" | \"https://admin-shell.io/zvei/nameplate/1/0/Nameplate/AssetSpecificProperties/GuidelineSpecificProperties\"]]	// OPTIONAL ENTRY\n"
			+ "		{\n"
			+ "			GuidelineForConformityDeclaration\n"
			+ "									:	\"GuidelineForConformityDeclaration\"\n"
			+ "																		[[SemanticId : \"IRDI\" | \"0173-1#02-AAO856#002\"]];\n"
			+ "			Arbitrary				:	\"Arbitrary3\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];\n"
			+ "			Arbitrary				:	\"Arbitrary4\"						[[SemanticId : \"Custom\" | \"Arbitrary\"]];	// OPTIONAL ENTRY\n"
			+ "		};\n"
			+ "		// Any number of \"GuidelineSpecificProperties\" Entries can be added here\n"
			+ "	};\n"
			+ "}";
	public String getFirstModelLine() {
		return "AAS :: Nameplate	\"" + ProjectName + "\"	[[SemanticId : \"IRI\" | \"https://www.hsu-hh.de/aut/aas/nameplate\"]]";
	}
	public String getContents()	{
		return Copyright + "\n\n" + getFirstModelLine() + "\n" + DefaultContents + "\n" + Footer + "\n";
	};	
}
