/*
 * generated by Xtext 2.23.0
 */
package org.xtext.smartaas.technicaldata.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.xtext.smartaas.technicaldata.ide.contentassist.antlr.internal.InternalDslParser;
import org.xtext.smartaas.technicaldata.services.DslGrammarAccess;

public class DslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(DslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, DslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getGroup(), "rule__TechnicaldataSubmodel__Group__0");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getGroup_10(), "rule__TechnicaldataSubmodel__Group_10__0");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getGroup_13(), "rule__TechnicaldataSubmodel__Group_13__0");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getGroup(), "rule__SubmodelElementCollectionGeneralInformation__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getGroup_9(), "rule__SubmodelElementCollectionGeneralInformation__Group_9__0");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getGroup_16(), "rule__SubmodelElementCollectionGeneralInformation__Group_16__0");
			builder.put(grammarAccess.getPropertyManufacturerNameAccess().getGroup(), "rule__PropertyManufacturerName__Group__0");
			builder.put(grammarAccess.getFileManufacturerLogoAccess().getGroup(), "rule__FileManufacturerLogo__Group__0");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getGroup(), "rule__MultiLanguagePropertyManufacturerProductDesignation__Group__0");
			builder.put(grammarAccess.getPropertyManufacturerPartNumberAccess().getGroup(), "rule__PropertyManufacturerPartNumber__Group__0");
			builder.put(grammarAccess.getPropertyManufacturerOrderCodeAccess().getGroup(), "rule__PropertyManufacturerOrderCode__Group__0");
			builder.put(grammarAccess.getFileProductImageAccess().getGroup(), "rule__FileProductImage__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationsAccess().getGroup(), "rule__SubmodelElementCollectionProductClassifications__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationsAccess().getGroup_7(), "rule__SubmodelElementCollectionProductClassifications__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getGroup(), "rule__SubmodelElementCollectionProductClassificationItem__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getGroup_9(), "rule__SubmodelElementCollectionProductClassificationItem__Group_9__0");
			builder.put(grammarAccess.getPropertyProductClassificationSystemAccess().getGroup(), "rule__PropertyProductClassificationSystem__Group__0");
			builder.put(grammarAccess.getPropertyClassificationSystemVersionAccess().getGroup(), "rule__PropertyClassificationSystemVersion__Group__0");
			builder.put(grammarAccess.getPropertyProductClassIdAccess().getGroup(), "rule__PropertyProductClassId__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getGroup(), "rule__SubmodelElementCollectionTechnicalProperties__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getGroup_7(), "rule__SubmodelElementCollectionTechnicalProperties__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getGroup_8(), "rule__SubmodelElementCollectionTechnicalProperties__Group_8__0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getGroup_9(), "rule__SubmodelElementCollectionTechnicalProperties__Group_9__0");
			builder.put(grammarAccess.getSubmodelElementArbitraryAccess().getGroup(), "rule__SubmodelElementArbitrary__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getGroup(), "rule__SubmodelElementCollectionSection__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getGroup_7(), "rule__SubmodelElementCollectionSection__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getGroup_8(), "rule__SubmodelElementCollectionSection__Group_8__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getGroup(), "rule__SubmodelElementCollectionSubSection__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getGroup_7(), "rule__SubmodelElementCollectionSubSection__Group_7__0");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getGroup_8(), "rule__SubmodelElementCollectionSubSection__Group_8__0");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getGroup(), "rule__SubmodelElementCollectionFurtherInformation__Group__0");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getGroup_7(), "rule__SubmodelElementCollectionFurtherInformation__Group_7__0");
			builder.put(grammarAccess.getMultiLanguagePropertyTextStatementAccess().getGroup(), "rule__MultiLanguagePropertyTextStatement__Group__0");
			builder.put(grammarAccess.getPropertyValidDateAccess().getGroup(), "rule__PropertyValidDate__Group__0");
			builder.put(grammarAccess.getSIDAccess().getGroup(), "rule__SID__Group__0");
			builder.put(grammarAccess.getModelAccess().getTechnicaldataAssignment(), "rule__Model__TechnicaldataAssignment");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getNameAssignment_3(), "rule__TechnicaldataSubmodel__NameAssignment_3");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getSemanticIdAssignment_5(), "rule__TechnicaldataSubmodel__SemanticIdAssignment_5");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getGeneralInformationAssignment_8(), "rule__TechnicaldataSubmodel__GeneralInformationAssignment_8");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getProductClassificationsAssignment_10_0(), "rule__TechnicaldataSubmodel__ProductClassificationsAssignment_10_0");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getTechnicalPropertiesAssignment_11(), "rule__TechnicaldataSubmodel__TechnicalPropertiesAssignment_11");
			builder.put(grammarAccess.getTechnicaldataSubmodelAccess().getFurtherInformationAssignment_13_0(), "rule__TechnicaldataSubmodel__FurtherInformationAssignment_13_0");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionGeneralInformation__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionGeneralInformation__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getManufacturerNameAssignment_7(), "rule__SubmodelElementCollectionGeneralInformation__ManufacturerNameAssignment_7");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getManufacturerLogoAssignment_9_0(), "rule__SubmodelElementCollectionGeneralInformation__ManufacturerLogoAssignment_9_0");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getManufacturerProductDesignationAssignment_10(), "rule__SubmodelElementCollectionGeneralInformation__ManufacturerProductDesignationAssignment_10");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getManufacturerPartNumberAssignment_12(), "rule__SubmodelElementCollectionGeneralInformation__ManufacturerPartNumberAssignment_12");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getManufacturerOrderCodeAssignment_14(), "rule__SubmodelElementCollectionGeneralInformation__ManufacturerOrderCodeAssignment_14");
			builder.put(grammarAccess.getSubmodelElementCollectionGeneralInformationAccess().getProductImageAssignment_16_0(), "rule__SubmodelElementCollectionGeneralInformation__ProductImageAssignment_16_0");
			builder.put(grammarAccess.getPropertyManufacturerNameAccess().getNameAssignment_2(), "rule__PropertyManufacturerName__NameAssignment_2");
			builder.put(grammarAccess.getPropertyManufacturerNameAccess().getSemanticIdAssignment_4(), "rule__PropertyManufacturerName__SemanticIdAssignment_4");
			builder.put(grammarAccess.getFileManufacturerLogoAccess().getNameAssignment_2(), "rule__FileManufacturerLogo__NameAssignment_2");
			builder.put(grammarAccess.getFileManufacturerLogoAccess().getSemanticIdAssignment_4(), "rule__FileManufacturerLogo__SemanticIdAssignment_4");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyManufacturerProductDesignation__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyManufacturerProductDesignationAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyManufacturerProductDesignation__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyManufacturerPartNumberAccess().getNameAssignment_2(), "rule__PropertyManufacturerPartNumber__NameAssignment_2");
			builder.put(grammarAccess.getPropertyManufacturerPartNumberAccess().getSemanticIdAssignment_4(), "rule__PropertyManufacturerPartNumber__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyManufacturerOrderCodeAccess().getNameAssignment_2(), "rule__PropertyManufacturerOrderCode__NameAssignment_2");
			builder.put(grammarAccess.getPropertyManufacturerOrderCodeAccess().getSemanticIdAssignment_4(), "rule__PropertyManufacturerOrderCode__SemanticIdAssignment_4");
			builder.put(grammarAccess.getFileProductImageAccess().getNameAssignment_2(), "rule__FileProductImage__NameAssignment_2");
			builder.put(grammarAccess.getFileProductImageAccess().getSemanticIdAssignment_4(), "rule__FileProductImage__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationsAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionProductClassifications__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationsAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionProductClassifications__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationsAccess().getProductClassificationItemAssignment_7_0(), "rule__SubmodelElementCollectionProductClassifications__ProductClassificationItemAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionProductClassificationItem__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionProductClassificationItem__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getProductClassificationSystemAssignment_7(), "rule__SubmodelElementCollectionProductClassificationItem__ProductClassificationSystemAssignment_7");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getClassificationSystemVersionAssignment_9_0(), "rule__SubmodelElementCollectionProductClassificationItem__ClassificationSystemVersionAssignment_9_0");
			builder.put(grammarAccess.getSubmodelElementCollectionProductClassificationItemAccess().getProductClassIdAssignment_10(), "rule__SubmodelElementCollectionProductClassificationItem__ProductClassIdAssignment_10");
			builder.put(grammarAccess.getPropertyProductClassificationSystemAccess().getNameAssignment_2(), "rule__PropertyProductClassificationSystem__NameAssignment_2");
			builder.put(grammarAccess.getPropertyProductClassificationSystemAccess().getSemanticIdAssignment_4(), "rule__PropertyProductClassificationSystem__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyClassificationSystemVersionAccess().getNameAssignment_2(), "rule__PropertyClassificationSystemVersion__NameAssignment_2");
			builder.put(grammarAccess.getPropertyClassificationSystemVersionAccess().getSemanticIdAssignment_4(), "rule__PropertyClassificationSystemVersion__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyProductClassIdAccess().getNameAssignment_2(), "rule__PropertyProductClassId__NameAssignment_2");
			builder.put(grammarAccess.getPropertyProductClassIdAccess().getSemanticIdAssignment_4(), "rule__PropertyProductClassId__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionTechnicalProperties__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionTechnicalProperties__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getArbitraryAssignment_7_0(), "rule__SubmodelElementCollectionTechnicalProperties__ArbitraryAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getSectionAssignment_8_0(), "rule__SubmodelElementCollectionTechnicalProperties__SectionAssignment_8_0");
			builder.put(grammarAccess.getSubmodelElementCollectionTechnicalPropertiesAccess().getSubSectionAssignment_9_0(), "rule__SubmodelElementCollectionTechnicalProperties__SubSectionAssignment_9_0");
			builder.put(grammarAccess.getSubmodelElementArbitraryAccess().getNameAssignment_2(), "rule__SubmodelElementArbitrary__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementArbitraryAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementArbitrary__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionSection__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionSection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getArbitraryAssignment_7_0(), "rule__SubmodelElementCollectionSection__ArbitraryAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionSectionAccess().getSubSectionAssignment_8_0(), "rule__SubmodelElementCollectionSection__SubSectionAssignment_8_0");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionSubSection__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionSubSection__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getArbitraryAssignment_7_0(), "rule__SubmodelElementCollectionSubSection__ArbitraryAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionSubSectionAccess().getSubSectionAssignment_8_0(), "rule__SubmodelElementCollectionSubSection__SubSectionAssignment_8_0");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getNameAssignment_2(), "rule__SubmodelElementCollectionFurtherInformation__NameAssignment_2");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getSemanticIdAssignment_4(), "rule__SubmodelElementCollectionFurtherInformation__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getTextStatementAssignment_7_0(), "rule__SubmodelElementCollectionFurtherInformation__TextStatementAssignment_7_0");
			builder.put(grammarAccess.getSubmodelElementCollectionFurtherInformationAccess().getValidDateAssignment_8(), "rule__SubmodelElementCollectionFurtherInformation__ValidDateAssignment_8");
			builder.put(grammarAccess.getMultiLanguagePropertyTextStatementAccess().getNameAssignment_2(), "rule__MultiLanguagePropertyTextStatement__NameAssignment_2");
			builder.put(grammarAccess.getMultiLanguagePropertyTextStatementAccess().getSemanticIdAssignment_4(), "rule__MultiLanguagePropertyTextStatement__SemanticIdAssignment_4");
			builder.put(grammarAccess.getPropertyValidDateAccess().getNameAssignment_2(), "rule__PropertyValidDate__NameAssignment_2");
			builder.put(grammarAccess.getPropertyValidDateAccess().getSemanticIdAssignment_4(), "rule__PropertyValidDate__SemanticIdAssignment_4");
			builder.put(grammarAccess.getSIDAccess().getNameAssignment_2(), "rule__SID__NameAssignment_2");
			builder.put(grammarAccess.getSIDAccess().getIIAssignment_4(), "rule__SID__IIAssignment_4");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private DslGrammarAccess grammarAccess;

	@Override
	protected InternalDslParser createParser() {
		InternalDslParser result = new InternalDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public DslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(DslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
