//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#ifndef CMATRIXDOUBLE22_JSON_TRANSFORMATION_H_
#define CMATRIXDOUBLE22_JSON_TRANSFORMATION_H_

#include <nlohmann/json.hpp>

#include <CommLocalizationObjects/CMatrixDouble22Data.hh>

namespace CommLocalizationObjectsIDL {

	void to_json(const CommLocalizationObjectsIDL::CMatrixDouble22& obj, nlohmann::json& j);
	void from_json(const nlohmann::json& j, CommLocalizationObjectsIDL::CMatrixDouble22& obj);
	
} // end namespace CommLocalizationObjectsIDL

#endif // CMATRIXDOUBLE22_JSON_TRANSFORMATION_H_
