//-----------------------------------------------------------------------------------
// Code generated by the Toolify Robotics GmbH extension for the SmartMDSD Toolchain 
// 
// Toolify Robotics GmbH
// Weinbergweg 216
// 89075 Ulm 
//
// Information about the SmartSoft MDSD Toolchain is available at:
// www.servicerobotik-ulm.de
//
// Please do not modify this file. It will be re-generated
// running the code generator.
//-----------------------------------------------------------------------------------

#include "CommLocalizationZoneResultJSON.hh"

#include "CommBasicObjectsJSON/CommTimeStampJSON.hh"

namespace CommLocalizationObjectsIDL {

void to_json(const CommLocalizationObjectsIDL::CommLocalizationZoneResult& obj, nlohmann::json& j)
{
	// currentZone: Int32
	j["currentZone"] = obj.currentZone;
	// timestamp: CommTimeStamp
	to_json(obj.timestamp, j["timestamp"]);
}

/**
 * this transformation handles missing values and checks for correct types:
 * - missing primitive type values (including simple arrays) are set to zero values
 * - missing object type values are skipped entirely
 * - types are checked before performing the type-cast operation
 */
void from_json(const nlohmann::json& j, CommLocalizationObjectsIDL::CommLocalizationZoneResult& obj)
{
	// currentZone: Int32
	if(j.contains("currentZone") && j["currentZone"].is_number_integer()) {
		obj.currentZone = j["currentZone"].get<int>();
	}
	// timestamp: CommTimeStamp
	if(j.contains("timestamp") && j["timestamp"].is_object()) {
		//from_json(j["timestamp"], obj.timestamp);
		obj.timestamp = j["timestamp"].get<CommBasicObjectsIDL::CommTimeStamp>();
	}
}

} // end namespace CommLocalizationObjectsIDL
